-- This CLP file was created using DB2LOOK Version 9.1
-- Timestamp: 公元2008年08月07日  星期四  15时59分18秒
-- Database Name: AFA            
-- Database Manager Version: DB2/AIX64 Version 9.1.0       
-- Database Codepage: 1386
-- Database Collating Sequence is: UNIQUE


--CONNECT TO AFA USER AFA USING AFA;



---------------------------------
-- DDL Statements for Sequences
---------------------------------

CREATE SEQUENCE "AFA     "."RCC_SEQ" AS INTEGER
	MINVALUE 1 MAXVALUE 99999999
	START WITH 1 INCREMENT BY 1
	CACHE 10 CYCLE NO ORDER;

ALTER SEQUENCE "AFA     "."RCC_SEQ" RESTART WITH 183819;

CREATE SEQUENCE "AFA     "."RCCPS_SEQ" AS INTEGER
	MINVALUE 1 MAXVALUE 999999
	START WITH 1 INCREMENT BY 1
	CACHE 10 CYCLE NO ORDER;

ALTER SEQUENCE "AFA     "."RCCPS_SEQ" RESTART WITH 191679;

CREATE SEQUENCE "AFA     "."TYHD_SEQ" AS INTEGER
	MINVALUE 1 MAXVALUE 9999
	START WITH 1 INCREMENT BY 1
	CACHE 10 CYCLE NO ORDER;


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_HPCBKA"
------------------------------------------------
DROP TABLE "AFA     "."RCC_HPCBKA";

CREATE TABLE "AFA     "."RCC_HPCBKA"  (
		  "BJEDTE" VARCHAR(8) NOT NULL , 
		  "BSPSQN" VARCHAR(12) NOT NULL , 
		  "BRSFLG" VARCHAR(1) NOT NULL , 
		  "BESBNO" VARCHAR(10) , 
		  "BETELR" VARCHAR(6) , 
		  "BEAUUS" VARCHAR(6) , 
		  "NCCWKDAT" VARCHAR(8) , 
		  "TRCCO" VARCHAR(7) , 
		  "TRCDAT" VARCHAR(8) , 
		  "TRCNO" VARCHAR(8) , 
		  "SNDMBRCO" VARCHAR(10) , 
		  "RCVMBRCO" VARCHAR(10) , 
		  "SNDBNKCO" VARCHAR(10) , 
		  "SNDBNKNM" VARCHAR(60) , 
		  "RCVBNKCO" VARCHAR(10) , 
		  "RCVBNKNM" VARCHAR(60) , 
		  "BOJEDT" VARCHAR(8) , 
		  "BOSPSQ" VARCHAR(12) , 
		  "ORTRCCO" VARCHAR(7) , 
		  "BILVER" VARCHAR(2) , 
		  "BILNO" VARCHAR(8) , 
		  "BILDAT" VARCHAR(8) , 
		  "PAYWAY" VARCHAR(1) , 
		  "CUR" VARCHAR(3) , 
		  "BILAMT" DECIMAL(15,2) , 
		  "PYRACC" VARCHAR(32) , 
		  "PYRNAM" VARCHAR(60) , 
		  "PYEACC" VARCHAR(32) , 
		  "PYENAM" VARCHAR(60) , 
		  "CONT" VARCHAR(255) , 
		  "ISDEAL" VARCHAR(1) , 
		  "PRCCO" VARCHAR(8) , 
		  "STRINFO" VARCHAR(60) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."BEAUUS" IS '授权柜员号';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."BESBNO" IS '机构号';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."BETELR" IS '柜员号';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."BILAMT" IS '出票金额';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."BILDAT" IS '出票日期';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."BILNO" IS '汇票号码';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."BILVER" IS '汇票版本号';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."BJEDTE" IS '报单日期';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."BOJEDT" IS '原报单日期';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."BOSPSQ" IS '原报单序号';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."BRSFLG" IS '往来标识(0-往账;1-来账)';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."BSPSQN" IS '报单序号';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."CONT" IS '内容';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."CUR" IS '币种';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."ISDEAL" IS '查询查复标识(0-未查复;1-已查复)';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."ORTRCCO" IS '原交易代码';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."PAYWAY" IS '兑付方式';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."PRCCO" IS '中心返回代码';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."PYEACC" IS '收款人账号';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."PYENAM" IS '收款人户名';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."PYRACC" IS '出票人账号';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."PYRNAM" IS '出票人户名';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."RCVBNKCO" IS '接收行行号';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."RCVBNKNM" IS '接收行行名';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."RCVMBRCO" IS '接收成员行号';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."SNDBNKCO" IS '发送行行号';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."SNDBNKNM" IS '发送行行名';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."SNDMBRCO" IS '发送成员行号';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."STRINFO" IS '中心返回代码说明';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."TRCCO" IS '交易代码';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."TRCDAT" IS '交易日期';

COMMENT ON COLUMN "AFA     "."RCC_HPCBKA"."TRCNO" IS '交易流水号';


-- DDL Statements for primary key on Table "AFA     "."RCC_HPCBKA"

ALTER TABLE "AFA     "."RCC_HPCBKA" 
	ADD CONSTRAINT "RCC_HPCBKA_PK" PRIMARY KEY
		("BJEDTE",
		 "BSPSQN");



------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_ATRCHK"
------------------------------------------------
DROP TABLE "AFA     "."RCC_ATRCHK";

CREATE TABLE "AFA     "."RCC_ATRCHK"  (
		  "SNDBNKCO" VARCHAR(10) NOT NULL , 
		  "TRCDAT" VARCHAR(8) NOT NULL , 
		  "TRCNO" VARCHAR(8) NOT NULL , 
		  "ROPRTPNO" VARCHAR(2) , 
		  "TRCCO" VARCHAR(7) , 
		  "RCVBNKCO" VARCHAR(10) , 
		  "CUR" VARCHAR(3) , 
		  "RDTCNT" DECIMAL(10,0) , 
		  "RDTAMT" DECIMAL(15,2) , 
		  "RCTCNT" DECIMAL(10,0) , 
		  "RCTAMT" DECIMAL(15,2) , 
		  "SDTCNT" DECIMAL(10,0) , 
		  "SDTAMT" DECIMAL(15,2) , 
		  "SCTCNT" DECIMAL(10,0) , 
		  "SCTAMT" DECIMAL(15,2) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."CUR" IS '币种';

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."RCTAMT" IS '来账贷记总金额';

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."RCTCNT" IS '来账贷记总笔数';

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."RCVBNKCO" IS '接收行行号';

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."RDTAMT" IS '来账借记总金额';

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."RDTCNT" IS '来账借记总笔数';

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."ROPRTPNO" IS '原业务种类';

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."SCTAMT" IS '往账贷记总金额';

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."SCTCNT" IS '往账贷记总笔数';

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."SDTAMT" IS '往账借记总金额';

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."SDTCNT" IS '往账借记总笔数';

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."SNDBNKCO" IS '发送行行号';

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."TRCCO" IS '交易代码';

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."TRCDAT" IS '委托日期';

COMMENT ON COLUMN "AFA     "."RCC_ATRCHK"."TRCNO" IS '交易流水号';


-- DDL Statements for primary key on Table "AFA     "."RCC_ATRCHK"

ALTER TABLE "AFA     "."RCC_ATRCHK" 
	ADD CONSTRAINT "RCC_ATRCHK_PK" PRIMARY KEY
		("SNDBNKCO",
		 "TRCDAT",
		 "TRCNO");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_CADBNK"
------------------------------------------------
DROP TABLE "AFA     "."RCC_ATRCHK";

CREATE TABLE "AFA     "."RCC_CADBNK"  (
		  "CARDBIN" VARCHAR(8) NOT NULL , 
		  "BANKBIN" VARCHAR(10) NOT NULL , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_CADBNK"."BANKBIN" IS '行号';

COMMENT ON COLUMN "AFA     "."RCC_CADBNK"."CARDBIN" IS '卡BIN';

COMMENT ON COLUMN "AFA     "."RCC_CADBNK"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_CADBNK"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_CADBNK"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_CADBNK"."NOTE4" IS '附加字段4';


-- DDL Statements for primary key on Table "AFA     "."RCC_CADBNK"

ALTER TABLE "AFA     "."RCC_CADBNK" 
	ADD CONSTRAINT "RCC_CADBNK_PK" PRIMARY KEY
		("CARDBIN");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_CSHALM"
------------------------------------------------
DROP TABLE "AFA     "."RCC_CSHALM";

CREATE TABLE "AFA     "."RCC_CSHALM"  (
		  "BJEDTE" VARCHAR(8) NOT NULL , 
		  "BSPSQN" VARCHAR(12) NOT NULL , 
		  "NCCWKDAT" VARCHAR(8) , 
		  "TRCCO" VARCHAR(7) , 
		  "TRCDAT" VARCHAR(8) , 
		  "TRCNO" VARCHAR(8) , 
		  "SNDBNKCO" VARCHAR(10) , 
		  "SNDBNKNM" VARCHAR(60) , 
		  "RCVBNKCO" VARCHAR(10) , 
		  "RCVBNKNM" VARCHAR(60) , 
		  "CUR" VARCHAR(3) , 
		  "POSITION" DECIMAL(15,2) , 
		  "POSALAMT" DECIMAL(15,2) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_CSHALM"."BJEDTE" IS '报单日期';

COMMENT ON COLUMN "AFA     "."RCC_CSHALM"."BSPSQN" IS '报单序号';

COMMENT ON COLUMN "AFA     "."RCC_CSHALM"."CUR" IS '币种';

COMMENT ON COLUMN "AFA     "."RCC_CSHALM"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_CSHALM"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_CSHALM"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_CSHALM"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_CSHALM"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_CSHALM"."POSALAMT" IS '头寸预警金额';

COMMENT ON COLUMN "AFA     "."RCC_CSHALM"."POSITION" IS '头寸当前余额';

COMMENT ON COLUMN "AFA     "."RCC_CSHALM"."RCVBNKCO" IS '接收行行号';

COMMENT ON COLUMN "AFA     "."RCC_CSHALM"."RCVBNKNM" IS '接收行行名';

COMMENT ON COLUMN "AFA     "."RCC_CSHALM"."SNDBNKCO" IS '发送行行号';

COMMENT ON COLUMN "AFA     "."RCC_CSHALM"."SNDBNKNM" IS '发送行行名';

COMMENT ON COLUMN "AFA     "."RCC_CSHALM"."TRCCO" IS '交易代码';

COMMENT ON COLUMN "AFA     "."RCC_CSHALM"."TRCDAT" IS '交易日期';

COMMENT ON COLUMN "AFA     "."RCC_CSHALM"."TRCNO" IS '交易流水号';


-- DDL Statements for primary key on Table "AFA     "."RCC_CSHALM"

ALTER TABLE "AFA     "."RCC_CSHALM" 
	ADD CONSTRAINT "RCC_CSHALM_PK" PRIMARY KEY
		("BJEDTE",
		 "BSPSQN");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_ERRINF"
------------------------------------------------
DROP TABLE "AFA     "."RCC_ERRINF";

CREATE TABLE "AFA     "."RCC_ERRINF"  (
		  "MBRTYP" VARCHAR(1) NOT NULL , 
		  "ERRKEY" VARCHAR(8) NOT NULL , 
		  "ERRSTR" VARCHAR(255) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_ERRINF"."ERRKEY" IS '中心返回代码';

COMMENT ON COLUMN "AFA     "."RCC_ERRINF"."ERRSTR" IS '中心返回代码说明';

COMMENT ON COLUMN "AFA     "."RCC_ERRINF"."MBRTYP" IS '成员方类型';

COMMENT ON COLUMN "AFA     "."RCC_ERRINF"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_ERRINF"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_ERRINF"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_ERRINF"."NOTE4" IS '附加字段4';


-- DDL Statements for primary key on Table "AFA     "."RCC_ERRINF"

ALTER TABLE "AFA     "."RCC_ERRINF" 
	ADD CONSTRAINT "RCC_ERRINF_PK" PRIMARY KEY
		("MBRTYP",
		 "ERRKEY");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_HDDZCZ"
------------------------------------------------
DROP TABLE "AFA     "."RCC_HDDZCZ";

CREATE TABLE "AFA     "."RCC_HDDZCZ"  (
		  "SNDBNKCO" VARCHAR(10) NOT NULL , 
		  "TRCDAT" VARCHAR(8) NOT NULL , 
		  "TRCNO" VARCHAR(8) NOT NULL , 
		  "NCCWKDAT" VARCHAR(8) , 
		  "BJEDTE" VARCHAR(8) , 
		  "BSPSQN" VARCHAR(12) , 
		  "EACTYP" VARCHAR(2) , 
		  "EACINF" VARCHAR(60) , 
		  "ISDEAL" VARCHAR(1) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_HDDZCZ"."BJEDTE" IS '报单日期';

COMMENT ON COLUMN "AFA     "."RCC_HDDZCZ"."BSPSQN" IS '报单序号';

COMMENT ON COLUMN "AFA     "."RCC_HDDZCZ"."EACINF" IS '错账类型说明';

COMMENT ON COLUMN "AFA     "."RCC_HDDZCZ"."EACTYP" IS '错账类型';

COMMENT ON COLUMN "AFA     "."RCC_HDDZCZ"."ISDEAL" IS '处理标识';

COMMENT ON COLUMN "AFA     "."RCC_HDDZCZ"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_HDDZCZ"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_HDDZCZ"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_HDDZCZ"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_HDDZCZ"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_HDDZCZ"."SNDBNKCO" IS '发送行行号';

COMMENT ON COLUMN "AFA     "."RCC_HDDZCZ"."TRCDAT" IS '委托日期';

COMMENT ON COLUMN "AFA     "."RCC_HDDZCZ"."TRCNO" IS '交易流水号';





------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_HDDZHZ"
------------------------------------------------
DROP TABLE "AFA     "."RCC_HDDZHZ";

CREATE TABLE "AFA     "."RCC_HDDZHZ"  (
		  "NCCWKDAT" VARCHAR(8) NOT NULL , 
		  "TRCCO" VARCHAR(7) NOT NULL , 
		  "BRSFLG" VARCHAR(1) NOT NULL , 
		  "TRCNAM" VARCHAR(60) , 
		  "TRCRSNM" VARCHAR(60) , 
		  "TCNT" SMALLINT NOT NULL , 
		  "CTAMT" DECIMAL(16,2) , 
		  "DTAMT" DECIMAL(16,2) , 
		  "OFSTAMT" DECIMAL(16,2) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_HDDZHZ"."BRSFLG" IS '往来标识(0-往账;1-来账)';

COMMENT ON COLUMN "AFA     "."RCC_HDDZHZ"."CTAMT" IS '贷方汇总金额';

COMMENT ON COLUMN "AFA     "."RCC_HDDZHZ"."DTAMT" IS '借方汇总金额';

COMMENT ON COLUMN "AFA     "."RCC_HDDZHZ"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_HDDZHZ"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_HDDZHZ"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_HDDZHZ"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_HDDZHZ"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_HDDZHZ"."OFSTAMT" IS '轧差汇总金额';

COMMENT ON COLUMN "AFA     "."RCC_HDDZHZ"."TCNT" IS '汇总笔数';

COMMENT ON COLUMN "AFA     "."RCC_HDDZHZ"."TRCCO" IS '交易代码';

COMMENT ON COLUMN "AFA     "."RCC_HDDZHZ"."TRCNAM" IS '交易名称';

COMMENT ON COLUMN "AFA     "."RCC_HDDZHZ"."TRCRSNM" IS '往来标识中文说明';


-- DDL Statements for primary key on Table "AFA     "."RCC_HDDZHZ"

ALTER TABLE "AFA     "."RCC_HDDZHZ" 
	ADD CONSTRAINT "RCC_HDDZHZ_PK" PRIMARY KEY
		("NCCWKDAT",
		 "TRCCO",
		 "BRSFLG");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_HPDZCZ"
------------------------------------------------
DROP TABLE "AFA     "."RCC_HPDZCZ";

CREATE TABLE "AFA     "."RCC_HPDZCZ"  (
		  "SNDBNKCO" VARCHAR(10) NOT NULL , 
		  "TRCDAT" VARCHAR(8) NOT NULL , 
		  "TRCNO" VARCHAR(8) NOT NULL , 
		  "NCCWKDAT" VARCHAR(8) , 
		  "BJEDTE" VARCHAR(8) , 
		  "BSPSQN" VARCHAR(12) , 
		  "EACTYP" VARCHAR(2) , 
		  "EACINF" VARCHAR(60) , 
		  "ISDEAL" VARCHAR(1) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_HPDZCZ"."BJEDTE" IS '报单日期';

COMMENT ON COLUMN "AFA     "."RCC_HPDZCZ"."BSPSQN" IS '报单序号';

COMMENT ON COLUMN "AFA     "."RCC_HPDZCZ"."EACINF" IS '错账类型说明';

COMMENT ON COLUMN "AFA     "."RCC_HPDZCZ"."EACTYP" IS '错账类型';

COMMENT ON COLUMN "AFA     "."RCC_HPDZCZ"."ISDEAL" IS '查复标识(0-未查复;1-已查复)';

COMMENT ON COLUMN "AFA     "."RCC_HPDZCZ"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_HPDZCZ"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_HPDZCZ"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_HPDZCZ"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_HPDZCZ"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_HPDZCZ"."SNDBNKCO" IS '发送行行号';

COMMENT ON COLUMN "AFA     "."RCC_HPDZCZ"."TRCDAT" IS '委托日期';

COMMENT ON COLUMN "AFA     "."RCC_HPDZCZ"."TRCNO" IS '交易流水号';





------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_HPDZHZ"
------------------------------------------------
DROP TABLE "AFA     "."RCC_HPDZHZ"

CREATE TABLE "AFA     "."RCC_HPDZHZ"  (
		  "NCCWKDAT" VARCHAR(8) NOT NULL , 
		  "TRCCO" VARCHAR(7) NOT NULL , 
		  "BRSFLG" VARCHAR(1) NOT NULL , 
		  "TRCNAM" VARCHAR(60) , 
		  "TRCRSNM" VARCHAR(60) , 
		  "TCNT" SMALLINT NOT NULL , 
		  "CTAMT" DECIMAL(16,2) , 
		  "DTAMT" DECIMAL(16,2) , 
		  "OFSTAMT" DECIMAL(16,2) , 
		  "CLAMT" DECIMAL(16,2) , 
		  "DLAMT" DECIMAL(16,2) , 
		  "OFSLAMT" DECIMAL(16,2) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_HPDZHZ"."BRSFLG" IS '往来标识(0-往账;1-来账)';

COMMENT ON COLUMN "AFA     "."RCC_HPDZHZ"."CLAMT" IS '贷方圈存金额';

COMMENT ON COLUMN "AFA     "."RCC_HPDZHZ"."CTAMT" IS '贷方汇总金额';

COMMENT ON COLUMN "AFA     "."RCC_HPDZHZ"."DLAMT" IS '借方圈存金额';

COMMENT ON COLUMN "AFA     "."RCC_HPDZHZ"."DTAMT" IS '借方汇总金额';

COMMENT ON COLUMN "AFA     "."RCC_HPDZHZ"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_HPDZHZ"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_HPDZHZ"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_HPDZHZ"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_HPDZHZ"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_HPDZHZ"."OFSLAMT" IS '轧差圈存金额';

COMMENT ON COLUMN "AFA     "."RCC_HPDZHZ"."OFSTAMT" IS '轧差汇总金额';

COMMENT ON COLUMN "AFA     "."RCC_HPDZHZ"."TCNT" IS '汇总笔数';

COMMENT ON COLUMN "AFA     "."RCC_HPDZHZ"."TRCCO" IS '交易代码';

COMMENT ON COLUMN "AFA     "."RCC_HPDZHZ"."TRCNAM" IS '交易名称';

COMMENT ON COLUMN "AFA     "."RCC_HPDZHZ"."TRCRSNM" IS '往来标识说明';


-- DDL Statements for primary key on Table "AFA     "."RCC_HPDZHZ"

ALTER TABLE "AFA     "."RCC_HPDZHZ" 
	ADD CONSTRAINT "RCC_HPDZHZ_PK" PRIMARY KEY
		("NCCWKDAT",
		 "TRCCO",
		 "BRSFLG");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_HPDZMX"
------------------------------------------------
DROP TABLE "AFA     "."RCC_HPDZMX";

CREATE TABLE "AFA     "."RCC_HPDZMX"  (
		  "SNDBNKCO" VARCHAR(10) NOT NULL , 
		  "TRCDAT" VARCHAR(8) NOT NULL , 
		  "TRCNO" VARCHAR(8) NOT NULL , 
		  "NCCWKDAT" VARCHAR(8) , 
		  "MSGTYPCO" VARCHAR(6) , 
		  "RCVMBRCO" VARCHAR(10) , 
		  "SNDMBRCO" VARCHAR(10) , 
		  "TRCCO" VARCHAR(7) , 
		  "SNDBRHCO" VARCHAR(6) , 
		  "SNDCLKNO" VARCHAR(8) , 
		  "SNDTRDAT" VARCHAR(8) , 
		  "SNDTRTIM" VARCHAR(6) , 
		  "MSGFLGNO" VARCHAR(26) , 
		  "ORMFN" VARCHAR(26) , 
		  "OPRTYPNO" VARCHAR(2) , 
		  "ROPRTPNO" VARCHAR(2) , 
		  "SNDBNKNM" VARCHAR(60) , 
		  "RCVBNKCO" VARCHAR(10) , 
		  "RCVBNKNM" VARCHAR(60) , 
		  "CUR" VARCHAR(3) , 
		  "OCCAMT" DECIMAL(15,2) , 
		  "PYRACC" VARCHAR(32) , 
		  "PYRNAM" VARCHAR(60) , 
		  "PYRADDR" VARCHAR(60) , 
		  "PYEACC" VARCHAR(32) , 
		  "PYENAM" VARCHAR(60) , 
		  "PYEADDR" VARCHAR(60) , 
		  "OPRATTNO" VARCHAR(2) , 
		  "SEAL" VARCHAR(10) , 
		  "BILDAT" VARCHAR(8) , 
		  "BILNO" VARCHAR(8) , 
		  "BILVER" VARCHAR(2) , 
		  "PAYWAY" VARCHAR(1) , 
		  "BILAMT" DECIMAL(15,2) , 
		  "RMNAMT" DECIMAL(15,2) , 
		  "USE" VARCHAR(20) , 
		  "REMARK" VARCHAR(30) , 
		  "BJEDTE" VARCHAR(8) , 
		  "BSPSQN" VARCHAR(12) , 
		  "BCSTAT" VARCHAR(2) , 
		  "BDWFLG" VARCHAR(1) , 
		  "EACTYP" VARCHAR(1) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."BCSTAT" IS '业务状态';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."BDWFLG" IS '状态流转处理标识';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."BILAMT" IS '出票金额';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."BILDAT" IS '出票日期';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."BILNO" IS '汇票号码';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."BILVER" IS '汇票版本号';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."BJEDTE" IS '报单日期';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."BSPSQN" IS '报单序号';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."CUR" IS '币种';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."EACTYP" IS '错账类型';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."MSGFLGNO" IS '报文标识号';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."MSGTYPCO" IS '报文类代码';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."OCCAMT" IS '实际结算金额';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."OPRATTNO" IS '业务属性';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."OPRTYPNO" IS '业务类型';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."ORMFN" IS '原报文标识号';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."PAYWAY" IS '兑付方式';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."PYEACC" IS '收款人账号';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."PYEADDR" IS '收款人地址';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."PYENAM" IS '收款人户名';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."PYRACC" IS '付款人账号';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."PYRADDR" IS '付款人地址';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."PYRNAM" IS '付款人户名';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."RCVBNKCO" IS '接收行行号';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."RCVBNKNM" IS '接受行行名';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."RCVMBRCO" IS '接收成员行号';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."REMARK" IS '备注';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."RMNAMT" IS '结余金额';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."ROPRTPNO" IS '原业务类型';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."SEAL" IS '密押';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."SNDBNKCO" IS '发送行行号';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."SNDBNKNM" IS '发送行行名';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."SNDBRHCO" IS '发起行网点号';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."SNDCLKNO" IS '发起行柜员号';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."SNDMBRCO" IS '发送成员行号';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."SNDTRDAT" IS '发起行交易日期';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."SNDTRTIM" IS '发起行交易时间';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."TRCCO" IS '交易代码';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."TRCDAT" IS '委托日期';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."TRCNO" IS '交易流水号';

COMMENT ON COLUMN "AFA     "."RCC_HPDZMX"."USE" IS '用途';


-- DDL Statements for primary key on Table "AFA     "."RCC_HPDZMX"

ALTER TABLE "AFA     "."RCC_HPDZMX" 
	ADD CONSTRAINT "RCC_HPDZMX_PK" PRIMARY KEY
		("SNDBNKCO",
		 "TRCDAT",
		 "TRCNO");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_INSBKA"
------------------------------------------------
DROP TABLE "AFA     "."RCC_INSBKA";

CREATE TABLE "AFA     "."RCC_INSBKA"  (
		  "BJEDTE" VARCHAR(8) NOT NULL , 
		  "BSPSQN" VARCHAR(12) NOT NULL , 
		  "NCCWKDAT" VARCHAR(8) , 
		  "TRDT" VARCHAR(8) , 
		  "TLSQ" VARCHAR(10) , 
		  "SBAC" VARCHAR(32) , 
		  "RBAC" VARCHAR(32) , 
		  "DASQ" VARCHAR(8) , 
		  "MGID" VARCHAR(7) , 
		  "BDWFLG" VARCHAR(1) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_INSBKA"."BDWFLG" IS '处理标识';

COMMENT ON COLUMN "AFA     "."RCC_INSBKA"."BJEDTE" IS '报单日期';

COMMENT ON COLUMN "AFA     "."RCC_INSBKA"."BSPSQN" IS '报单序号';

COMMENT ON COLUMN "AFA     "."RCC_INSBKA"."DASQ" IS '待销账序号';

COMMENT ON COLUMN "AFA     "."RCC_INSBKA"."MGID" IS '主机返回码';

COMMENT ON COLUMN "AFA     "."RCC_INSBKA"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_INSBKA"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_INSBKA"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_INSBKA"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_INSBKA"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_INSBKA"."RBAC" IS '贷方账号';

COMMENT ON COLUMN "AFA     "."RCC_INSBKA"."SBAC" IS '借方账号';

COMMENT ON COLUMN "AFA     "."RCC_INSBKA"."TLSQ" IS '主机流水号';

COMMENT ON COLUMN "AFA     "."RCC_INSBKA"."TRDT" IS '主机日期';


-- DDL Statements for primary key on Table "AFA     "."RCC_INSBKA"

ALTER TABLE "AFA     "."RCC_INSBKA" 
	ADD CONSTRAINT "RCC_INSBKA_PK" PRIMARY KEY
		("BJEDTE",
		 "BSPSQN");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_MBRIFA"
------------------------------------------------
DROP TABLE "AFA     "."RCC_MBRIFA";

CREATE TABLE "AFA     "."RCC_MBRIFA"  (
		  "OPRTYPNO" VARCHAR(2) NOT NULL , 
		  "ORWKDAT" VARCHAR(8) NOT NULL , 
		  "ORSYSST" VARCHAR(2) NOT NULL , 
		  "NWWKDAT" VARCHAR(8) NOT NULL , 
		  "NWSYSST" VARCHAR(2) NOT NULL , 
		  "HOLFLG" VARCHAR(1) NOT NULL , 
		  "STRINFO" VARCHAR(60) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_MBRIFA"."HOLFLG" IS '工作日类型';

COMMENT ON COLUMN "AFA     "."RCC_MBRIFA"."NOTE1" IS '附加字段1(对账日期)';

COMMENT ON COLUMN "AFA     "."RCC_MBRIFA"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_MBRIFA"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_MBRIFA"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_MBRIFA"."NWSYSST" IS '当前中心工作状态';

COMMENT ON COLUMN "AFA     "."RCC_MBRIFA"."NWWKDAT" IS '当前中心工作日期';

COMMENT ON COLUMN "AFA     "."RCC_MBRIFA"."OPRTYPNO" IS '业务类型';

COMMENT ON COLUMN "AFA     "."RCC_MBRIFA"."ORSYSST" IS '前中心工作状态';

COMMENT ON COLUMN "AFA     "."RCC_MBRIFA"."ORWKDAT" IS '前中心工作日期';

COMMENT ON COLUMN "AFA     "."RCC_MBRIFA"."STRINFO" IS '附言';


-- DDL Statements for primary key on Table "AFA     "."RCC_MBRIFA"

ALTER TABLE "AFA     "."RCC_MBRIFA" 
	ADD CONSTRAINT "RCC_MBRIFA_PK" PRIMARY KEY
		("OPRTYPNO");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_PAMTBL"
------------------------------------------------
DROP TABLE "AFA     "."RCC_PAMTBL";

CREATE TABLE "AFA     "."RCC_PAMTBL"  (
		  "BPATPE" VARCHAR(1) NOT NULL , 
		  "BPARAD" VARCHAR(18) NOT NULL , 
		  "BPACMT" VARCHAR(60) , 
		  "BPADAT" VARCHAR(255) , 
		  "BPAINF" VARCHAR(60) , 
		  "BEFTDT" VARCHAR(8) , 
		  "BINVDT" VARCHAR(8) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_PAMTBL"."BEFTDT" IS '生效日期';

COMMENT ON COLUMN "AFA     "."RCC_PAMTBL"."BINVDT" IS '失效日期';

COMMENT ON COLUMN "AFA     "."RCC_PAMTBL"."BPACMT" IS '参数说明';

COMMENT ON COLUMN "AFA     "."RCC_PAMTBL"."BPADAT" IS '参数数据';

COMMENT ON COLUMN "AFA     "."RCC_PAMTBL"."BPAINF" IS '参数备注';

COMMENT ON COLUMN "AFA     "."RCC_PAMTBL"."BPARAD" IS '参数代码';

COMMENT ON COLUMN "AFA     "."RCC_PAMTBL"."BPATPE" IS '参数类型';

COMMENT ON COLUMN "AFA     "."RCC_PAMTBL"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_PAMTBL"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_PAMTBL"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_PAMTBL"."NOTE4" IS '附加字段4';


-- DDL Statements for primary key on Table "AFA     "."RCC_PAMTBL"

ALTER TABLE "AFA     "."RCC_PAMTBL" 
	ADD CONSTRAINT "RCC_PAMTBL_PK" PRIMARY KEY
		("BPATPE",
		 "BPARAD");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_SPBSTA"
------------------------------------------------
DROP TABLE "AFA     "."RCC_SPBSTA";

CREATE TABLE "AFA     "."RCC_SPBSTA"  (
		  "BJEDTE" VARCHAR(8) NOT NULL , 
		  "BSPSQN" VARCHAR(12) NOT NULL , 
		  "BCURSQ" SMALLINT NOT NULL , 
		  "BCSTAT" VARCHAR(2) , 
		  "BDWFLG" VARCHAR(1) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_SPBSTA"."BCSTAT" IS '业务状态';

COMMENT ON COLUMN "AFA     "."RCC_SPBSTA"."BCURSQ" IS '状态编号';

COMMENT ON COLUMN "AFA     "."RCC_SPBSTA"."BDWFLG" IS '流转处理标识';

COMMENT ON COLUMN "AFA     "."RCC_SPBSTA"."BJEDTE" IS '报单日期';

COMMENT ON COLUMN "AFA     "."RCC_SPBSTA"."BSPSQN" IS '报单序号';

COMMENT ON COLUMN "AFA     "."RCC_SPBSTA"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_SPBSTA"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_SPBSTA"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_SPBSTA"."NOTE4" IS '附加字段4';


-- DDL Statements for primary key on Table "AFA     "."RCC_SPBSTA"

ALTER TABLE "AFA     "."RCC_SPBSTA" 
	ADD CONSTRAINT "RCC_SPBSTA_PK" PRIMARY KEY
		("BJEDTE",
		 "BSPSQN");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_SUBBRA"
------------------------------------------------
DROP TABLE "AFA     "."RCC_SUBBRA";

CREATE TABLE "AFA     "."RCC_SUBBRA"  (
		  "BESBNO" VARCHAR(10) NOT NULL , 
		  "BESBNM" VARCHAR(60) , 
		  "BESBTP" VARCHAR(2) , 
		  "BTOPSB" VARCHAR(10) , 
		  "BEACSB" VARCHAR(10) , 
		  "BANKBIN" VARCHAR(10) , 
		  "SUBFLG" VARCHAR(1) , 
		  "STRINFO" VARCHAR(60) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_SUBBRA"."BANKBIN" IS '农信银系统行号';

COMMENT ON COLUMN "AFA     "."RCC_SUBBRA"."BEACSB" IS '账务机构号';

COMMENT ON COLUMN "AFA     "."RCC_SUBBRA"."BESBNM" IS '机构名称';

COMMENT ON COLUMN "AFA     "."RCC_SUBBRA"."BESBNO" IS '机构号';

COMMENT ON COLUMN "AFA     "."RCC_SUBBRA"."BESBTP" IS '机构类型';

COMMENT ON COLUMN "AFA     "."RCC_SUBBRA"."BTOPSB" IS '上级机构号';

COMMENT ON COLUMN "AFA     "."RCC_SUBBRA"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_SUBBRA"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_SUBBRA"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_SUBBRA"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_SUBBRA"."STRINFO" IS '附言';

COMMENT ON COLUMN "AFA     "."RCC_SUBBRA"."SUBFLG" IS '代理标识(0-被代理;1-代理)';


-- DDL Statements for primary key on Table "AFA     "."RCC_SUBBRA"

ALTER TABLE "AFA     "."RCC_SUBBRA" 
	ADD CONSTRAINT "RCC_SUBBRA_PK" PRIMARY KEY
		("BESBNO");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_TRCSTA"
------------------------------------------------
DROP TABLE "AFA     "."RCC_TRCSTA";

CREATE TABLE "AFA     "."RCC_TRCSTA"  (
		  "NCCWKDAT" VARCHAR(8) NOT NULL , 
		  "BESBNO" VARCHAR(10) NOT NULL , 
		  "TRCCO" VARCHAR(7) NOT NULL , 
		  "BRSFLG" VARCHAR(1) NOT NULL , 
		  "BTOPSB" VARCHAR(10) , 
		  "BEACSB" VARCHAR(10) , 
		  "TCNT" SMALLINT NOT NULL , 
		  "TAMT" DECIMAL(15,2) , 
		  "ISDEAL" VARCHAR(1) , 
		  "STRINFO" VARCHAR(60) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_TRCSTA"."BEACSB" IS '财务机构号';

COMMENT ON COLUMN "AFA     "."RCC_TRCSTA"."BESBNO" IS '机构号';

COMMENT ON COLUMN "AFA     "."RCC_TRCSTA"."BRSFLG" IS '往来标识(0-往账;1-来账)';

COMMENT ON COLUMN "AFA     "."RCC_TRCSTA"."BTOPSB" IS '上级机构号';

COMMENT ON COLUMN "AFA     "."RCC_TRCSTA"."ISDEAL" IS '处理标识(0-未处理;1-已处理)';

COMMENT ON COLUMN "AFA     "."RCC_TRCSTA"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_TRCSTA"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_TRCSTA"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_TRCSTA"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_TRCSTA"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_TRCSTA"."STRINFO" IS '附言';

COMMENT ON COLUMN "AFA     "."RCC_TRCSTA"."TAMT" IS '汇总金额';

COMMENT ON COLUMN "AFA     "."RCC_TRCSTA"."TCNT" IS '汇总笔数';

COMMENT ON COLUMN "AFA     "."RCC_TRCSTA"."TRCCO" IS '交易代码';


-- DDL Statements for primary key on Table "AFA     "."RCC_TRCSTA"

ALTER TABLE "AFA     "."RCC_TRCSTA" 
	ADD CONSTRAINT "RCC_TRCSTA_PK" PRIMARY KEY
		("NCCWKDAT",
		 "BESBNO",
		 "TRCCO",
		 "BRSFLG");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_SSTLOG"
------------------------------------------------
DROP TABLE "AFA     "."RCC_SSTLOG";

CREATE TABLE "AFA     "."RCC_SSTLOG"  (
		  "BJEDTE" VARCHAR(8) NOT NULL , 
		  "BSPSQN" VARCHAR(12) NOT NULL , 
		  "BCURSQ" SMALLINT NOT NULL , 
		  "BESBNO" VARCHAR(10) , 
		  "BEACSB" VARCHAR(10) , 
		  "BETELR" VARCHAR(6) , 
		  "BEAUUS" VARCHAR(6) , 
		  "FEDT" VARCHAR(8) , 
		  "RBSQ" VARCHAR(12) , 
		  "TRDT" VARCHAR(8) , 
		  "TLSQ" VARCHAR(10) , 
		  "SBAC" VARCHAR(32) , 
		  "ACNM" VARCHAR(60) , 
		  "RBAC" VARCHAR(32) , 
		  "OTNM" VARCHAR(60) , 
		  "DASQ" VARCHAR(9) , 
		  "MGID" VARCHAR(7) , 
		  "PRCCO" VARCHAR(8) , 
		  "STRINFO" VARCHAR(60) , 
		  "BCSTAT" VARCHAR(2) , 
		  "BDWFLG" VARCHAR(1) , 
		  "PRTCNT" SMALLINT NOT NULL , 
		  "BJETIM" VARCHAR(20) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."ACNM" IS '借方户名';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."BCSTAT" IS '业务状态';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."BCURSQ" IS '往来标识(0-往账;1-来账)';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."BDWFLG" IS '流转处理标识';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."BEACSB" IS '账务机构号';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."BEAUUS" IS '授权柜员号';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."BESBNO" IS '机构号';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."BETELR" IS '柜员号';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."BJEDTE" IS '报单日期';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."BJETIM" IS '交易时间';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."BSPSQN" IS '报单序号';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."DASQ" IS '销账序号';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."FEDT" IS '前置日期';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."MGID" IS '主机返回码';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."OTNM" IS '贷方户名';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."PRCCO" IS '中心返回码';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."PRTCNT" IS '打印次数';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."RBAC" IS '贷方账号';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."RBSQ" IS '前置流水号';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."SBAC" IS '借方账号';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."STRINFO" IS '返回码说明';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."TLSQ" IS '主机流水号';

COMMENT ON COLUMN "AFA     "."RCC_SSTLOG"."TRDT" IS '主机日期';


-- DDL Statements for primary key on Table "AFA     "."RCC_SSTLOG"

ALTER TABLE "AFA     "."RCC_SSTLOG" 
	ADD CONSTRAINT "RCC_SSTLOG_PK" PRIMARY KEY
		("BJEDTE",
		 "BSPSQN",
		 "BCURSQ");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_PBDATA"
------------------------------------------------
DROP TABLE "AFA     "."RCC_PBDATA";

CREATE TABLE "AFA     "."RCC_PBDATA"  (
		  "TRCDAT" VARCHAR(8) NOT NULL , 
		  "TRCNO" VARCHAR(8) NOT NULL , 
		  "SNDBNKCO" VARCHAR(10) NOT NULL , 
		  "NCCWKDAT" VARCHAR(8) , 
		  "TRCCO" VARCHAR(7) , 
		  "RCVBNKCO" VARCHAR(10) , 
		  "EFCTDAT" VARCHAR(8) , 
		  "PBDATYP" VARCHAR(3) , 
		  "PBDAFILE" VARCHAR(255) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_PBDATA"."EFCTDAT" IS '生效日期';

COMMENT ON COLUMN "AFA     "."RCC_PBDATA"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_PBDATA"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_PBDATA"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_PBDATA"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_PBDATA"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_PBDATA"."PBDAFILE" IS '公共数据文件名';

COMMENT ON COLUMN "AFA     "."RCC_PBDATA"."PBDATYP" IS '公共数据类型';

COMMENT ON COLUMN "AFA     "."RCC_PBDATA"."RCVBNKCO" IS '接收行行号';

COMMENT ON COLUMN "AFA     "."RCC_PBDATA"."SNDBNKCO" IS '发送行行号';

COMMENT ON COLUMN "AFA     "."RCC_PBDATA"."TRCCO" IS '交易代码';

COMMENT ON COLUMN "AFA     "."RCC_PBDATA"."TRCDAT" IS '委托日期';

COMMENT ON COLUMN "AFA     "."RCC_PBDATA"."TRCNO" IS '交易流水号';


-- DDL Statements for primary key on Table "AFA     "."RCC_PBDATA"

ALTER TABLE "AFA     "."RCC_PBDATA" 
	ADD CONSTRAINT "RCC_PBDATE_PK" PRIMARY KEY
		("TRCDAT",
		 "TRCNO",
		 "SNDBNKCO");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_PAYBNK"
------------------------------------------------
DROP TABLE "AFA     "."RCC_PAYBNK";

CREATE TABLE "AFA     "."RCC_PAYBNK"  (
		  "BANKBIN" VARCHAR(10) NOT NULL , 
		  "BANKSTATUS" VARCHAR(1) , 
		  "BANKATTR" VARCHAR(2) , 
		  "STLBANKBIN" VARCHAR(10) , 
		  "BANKNAM" VARCHAR(60) , 
		  "BANKADDR" VARCHAR(60) , 
		  "BANKPC" VARCHAR(6) , 
		  "BANKTEL" VARCHAR(30) , 
		  "EFCTDAT" VARCHAR(8) , 
		  "INVDAT" VARCHAR(8) , 
		  "ALTTYPE" VARCHAR(1) , 
		  "PRIVILEGE" VARCHAR(20) , 
		  "NEWOFLG" VARCHAR(1) , 
		  "STRINFO" VARCHAR(60) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_PAYBNK"."ALTTYPE" IS '最近更新操作';

COMMENT ON COLUMN "AFA     "."RCC_PAYBNK"."BANKADDR" IS '地址';

COMMENT ON COLUMN "AFA     "."RCC_PAYBNK"."BANKATTR" IS '属性';

COMMENT ON COLUMN "AFA     "."RCC_PAYBNK"."BANKBIN" IS '行号';

COMMENT ON COLUMN "AFA     "."RCC_PAYBNK"."BANKNAM" IS '参与者全称';

COMMENT ON COLUMN "AFA     "."RCC_PAYBNK"."BANKPC" IS '邮编';

COMMENT ON COLUMN "AFA     "."RCC_PAYBNK"."BANKSTATUS" IS '状态';

COMMENT ON COLUMN "AFA     "."RCC_PAYBNK"."BANKTEL" IS '电话';

COMMENT ON COLUMN "AFA     "."RCC_PAYBNK"."EFCTDAT" IS '生效日期';

COMMENT ON COLUMN "AFA     "."RCC_PAYBNK"."INVDAT" IS '失效日期';

COMMENT ON COLUMN "AFA     "."RCC_PAYBNK"."NEWOFLG" IS '新旧系统标识';

COMMENT ON COLUMN "AFA     "."RCC_PAYBNK"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_PAYBNK"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_PAYBNK"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_PAYBNK"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_PAYBNK"."PRIVILEGE" IS '业务权限';

COMMENT ON COLUMN "AFA     "."RCC_PAYBNK"."STLBANKBIN" IS '成员行号';

COMMENT ON COLUMN "AFA     "."RCC_PAYBNK"."STRINFO" IS '附言';


-- DDL Statements for primary key on Table "AFA     "."RCC_PAYBNK"

ALTER TABLE "AFA     "."RCC_PAYBNK" 
	ADD CONSTRAINT "RCC_PAYBNK_PK" PRIMARY KEY
		("BANKBIN");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_BILINF"
------------------------------------------------
DROP TABLE "AFA     "."RCC_BILINF";

CREATE TABLE "AFA     "."RCC_BILINF"  (
		  "BILVER" VARCHAR(2) NOT NULL , 
		  "BILNO" VARCHAR(8) NOT NULL , 
		  "BILRS" VARCHAR(1) NOT NULL , 
		  "BILTYP" VARCHAR(2) , 
		  "BILDAT" VARCHAR(8) , 
		  "PAYWAY" VARCHAR(1) , 
		  "REMBNKCO" VARCHAR(10) , 
		  "REMBNKNM" VARCHAR(60) , 
		  "PAYBNKCO" VARCHAR(10) , 
		  "PAYBNKNM" VARCHAR(60) , 
		  "PYRACC" VARCHAR(32) , 
		  "PYRNAM" VARCHAR(60) , 
		  "PYRADDR" VARCHAR(60) , 
		  "PYEACC" VARCHAR(32) , 
		  "PYENAM" VARCHAR(60) , 
		  "PYEADDR" VARCHAR(60) , 
		  "PYHACC" VARCHAR(32) , 
		  "PYHNAM" VARCHAR(60) , 
		  "PYHADDR" VARCHAR(60) , 
		  "PYITYP" VARCHAR(1) , 
		  "PYIACC" VARCHAR(32) , 
		  "PYINAM" VARCHAR(60) , 
		  "BILAMT" DECIMAL(15,2) , 
		  "OCCAMT" DECIMAL(15,2) , 
		  "RMNAMT" DECIMAL(15,2) , 
		  "CUR" VARCHAR(3) , 
		  "SEAL" VARCHAR(10) , 
		  "USE" VARCHAR(20) , 
		  "REMARK" VARCHAR(30) , 
		  "HPCUSQ" SMALLINT NOT NULL , 
		  "HPSTAT" VARCHAR(2) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" ; 

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."BILAMT" IS '出票金额';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."BILDAT" IS '出票日期';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."BILNO" IS '汇票号码';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."BILRS" IS '汇票本行他行标识(0-本行签发的汇票;1-他行签发的汇票)';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."BILTYP" IS '汇票种类(0-现金汇票;1-转账汇票)';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."BILVER" IS '汇票版本号';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."CUR" IS '币种';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."HPCUSQ" IS '汇票状态编号';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."HPSTAT" IS '汇票状态';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."OCCAMT" IS '实际结算金额';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."PAYBNKCO" IS '代理付款行行号';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."PAYBNKNM" IS '代理付款行行名';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."PAYWAY" IS '兑付方式(0-现金;1-非现金)';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."PYEACC" IS '收款人账号';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."PYEADDR" IS '收款人地址';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."PYENAM" IS '收款人户名';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."PYHACC" IS '持票人账号';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."PYHADDR" IS '持票人地址';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."PYHNAM" IS '持票人户名';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."PYIACC" IS '退票入账账号';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."PYINAM" IS '退票入账户名';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."PYITYP" IS '退票操作类型';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."PYRACC" IS '出票人账号';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."PYRADDR" IS '出票人地址';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."PYRNAM" IS '出票人户名';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."REMARK" IS '备注';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."REMBNKCO" IS '出票行行号';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."REMBNKNM" IS '出票行行名';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."RMNAMT" IS '结余金额';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."SEAL" IS '汇票密押';

COMMENT ON COLUMN "AFA     "."RCC_BILINF"."USE" IS '用途';


-- DDL Statements for primary key on Table "AFA     "."RCC_BILINF"

ALTER TABLE "AFA     "."RCC_BILINF" 
	ADD CONSTRAINT "RCC_BILINF_PK" PRIMARY KEY
		("BILVER",
		 "BILNO",
		 "BILRS");





------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_MRQTBL"
------------------------------------------------
DROP TABLE "AFA     "."RCC_MRQTBL";

CREATE TABLE "AFA     "."RCC_MRQTBL"  (
		  "BJEDTE" VARCHAR(8) NOT NULL , 
		  "BSPSQN" VARCHAR(12) NOT NULL , 
		  "TRCCO" VARCHAR(8) , 
		  "SNDBNKCO" VARCHAR(10) , 
		  "SNDBNKNM" VARCHAR(60) , 
		  "RCVBNKCO" VARCHAR(10) , 
		  "RCVBNKNM" VARCHAR(60) , 
		  "SNDMBRCO" VARCHAR(10) , 
		  "RCVMBRCO" VARCHAR(10) , 
		  "TRCDAT" VARCHAR(8) , 
		  "TRCNO" VARCHAR(8) , 
		  "NPCBKID" VARCHAR(12) , 
		  "NPCBKNM" VARCHAR(60) , 
		  "NPCACNT" VARCHAR(32) , 
		  "OCCAMT" DECIMAL(15,2) , 
		  "REMARK" VARCHAR(60) , 
		  "PRCCO" VARCHAR(8) , 
		  "STRINFO" VARCHAR(60) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."BJEDTE" IS '报单日期';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."BSPSQN" IS '报单序号';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."NPCACNT" IS '汇入支付系统账号';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."NPCBKID" IS '汇入支付系统行号';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."NPCBKNM" IS '汇入支付系统行名';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."OCCAMT" IS '调拨金额';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."PRCCO" IS '中心返回码';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."RCVBNKCO" IS '接收行行号';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."RCVBNKNM" IS '接收行行名';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."RCVMBRCO" IS '接收成员行号';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."REMARK" IS '备注';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."SNDBNKCO" IS '发送行行号';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."SNDBNKNM" IS '发送行行名';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."SNDMBRCO" IS '发送成员行号';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."STRINFO" IS '中心返回码说明';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."TRCCO" IS '交易代码';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."TRCDAT" IS '委托日期';

COMMENT ON COLUMN "AFA     "."RCC_MRQTBL"."TRCNO" IS '交易流水号';


-- DDL Statements for primary key on Table "AFA     "."RCC_MRQTBL"

ALTER TABLE "AFA     "."RCC_MRQTBL" 
	ADD CONSTRAINT "RCC_MRQTBL_PK" PRIMARY KEY
		("BJEDTE",
		 "BSPSQN");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_TRCCAN"
------------------------------------------------
DROP TABLE "AFA     "."RCC_TRCCAN";

CREATE TABLE "AFA     "."RCC_TRCCAN"  (
		  "BJEDTE" VARCHAR(8) NOT NULL , 
		  "BSPSQN" VARCHAR(12) NOT NULL , 
		  "BRSFLG" VARCHAR(1) , 
		  "BESBNO" VARCHAR(10) , 
		  "BETELR" VARCHAR(6) , 
		  "BEAUUS" VARCHAR(6) , 
		  "NCCWKDAT" VARCHAR(8) , 
		  "TRCCO" VARCHAR(7) , 
		  "TRCDAT" VARCHAR(8) , 
		  "TRCNO" VARCHAR(8) , 
		  "SNDMBRCO" VARCHAR(10) , 
		  "RCVMBRCO" VARCHAR(10) , 
		  "SNDBNKCO" VARCHAR(10) , 
		  "SNDBNKNM" VARCHAR(60) , 
		  "RCVBNKCO" VARCHAR(10) , 
		  "RCVBNKNM" VARCHAR(60) , 
		  "BOJEDT" VARCHAR(8) , 
		  "BOSPSQ" VARCHAR(12) , 
		  "ORTRCCO" VARCHAR(7) , 
		  "CUR" VARCHAR(3) , 
		  "OCCAMT" DECIMAL(15,2) , 
		  "CONT" VARCHAR(255) , 
		  "CLRESPN" VARCHAR(1) , 
		  "PRCCO" VARCHAR(8) , 
		  "STRINFO" VARCHAR(60) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."BEAUUS" IS '授权柜员号';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."BESBNO" IS '机构号';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."BETELR" IS '柜员号';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."BJEDTE" IS '报单日期';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."BOJEDT" IS '原报单日期';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."BOSPSQ" IS '原报单序号';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."BRSFLG" IS '往来标识(0-往账;1-来账)';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."BSPSQN" IS '报单序号';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."CLRESPN" IS '撤销应答(0-撤销;1-不能撤销)';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."CONT" IS '内容';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."CUR" IS '币种';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."OCCAMT" IS '交易金额';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."ORTRCCO" IS '原交易代码';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."PRCCO" IS '中心返回码';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."RCVBNKCO" IS '接收行行号';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."RCVBNKNM" IS '接受行行名';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."RCVMBRCO" IS '接收成员行号';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."SNDBNKCO" IS '发送行行号';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."SNDBNKNM" IS '发送行行名';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."SNDMBRCO" IS '发送成员行号';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."STRINFO" IS '中心返回码说明';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."TRCCO" IS '交易代码';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."TRCDAT" IS '委托日期';

COMMENT ON COLUMN "AFA     "."RCC_TRCCAN"."TRCNO" IS '交易流水号';


-- DDL Statements for primary key on Table "AFA     "."RCC_TRCCAN"

ALTER TABLE "AFA     "."RCC_TRCCAN" 
	ADD CONSTRAINT "RCC_TRCCAN_PK" PRIMARY KEY
		("BJEDTE",
		 "BSPSQN");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_EXISTP"
------------------------------------------------
DROP TABLE "AFA     "."RCC_EXISTP";

CREATE TABLE "AFA     "."RCC_EXISTP"  (
		  "BJEDTE" VARCHAR(8) NOT NULL , 
		  "BSPSQN" VARCHAR(12) NOT NULL , 
		  "BRSFLG" VARCHAR(1) , 
		  "BESBNO" VARCHAR(10) , 
		  "BETELR" VARCHAR(6) , 
		  "BEAUUS" VARCHAR(6) , 
		  "NCCWKDAT" VARCHAR(8) , 
		  "TRCCO" VARCHAR(7) , 
		  "TRCDAT" VARCHAR(8) , 
		  "TRCNO" VARCHAR(8) , 
		  "SNDMBRCO" VARCHAR(10) , 
		  "RCVMBRCO" VARCHAR(10) , 
		  "SNDBNKCO" VARCHAR(10) , 
		  "SNDBNKNM" VARCHAR(60) , 
		  "RCVBNKCO" VARCHAR(10) , 
		  "RCVBNKNM" VARCHAR(60) , 
		  "BOJEDT" VARCHAR(8) , 
		  "BOSPSQ" VARCHAR(12) , 
		  "ORTRCCO" VARCHAR(7) , 
		  "CUR" VARCHAR(3) , 
		  "OCCAMT" DECIMAL(15,2) , 
		  "CONT" VARCHAR(255) , 
		  "PRCCO" VARCHAR(8) , 
		  "STRINFO" VARCHAR(60) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."BEAUUS" IS '授权柜员号';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."BESBNO" IS '机构号';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."BETELR" IS '柜员号';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."BJEDTE" IS '报单日期';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."BOJEDT" IS '原报单日期';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."BOSPSQ" IS '原报单序号';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."BRSFLG" IS '往来标识(0-往账;1-来账)';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."BSPSQN" IS '报单序号';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."CONT" IS '内容';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."CUR" IS '币种';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."OCCAMT" IS '交易金额';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."ORTRCCO" IS '原交易代码';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."PRCCO" IS '中心返回码';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."RCVBNKCO" IS '接收行行号';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."RCVBNKNM" IS '接收行行名';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."RCVMBRCO" IS '接收成员行号';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."SNDBNKCO" IS '发送行行号';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."SNDBNKNM" IS '发送行行名';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."SNDMBRCO" IS '发送成员行号';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."STRINFO" IS '中心返回码说明';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."TRCCO" IS '交易代码';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."TRCDAT" IS '委托日期';

COMMENT ON COLUMN "AFA     "."RCC_EXISTP"."TRCNO" IS '交易流水号';


-- DDL Statements for primary key on Table "AFA     "."RCC_EXISTP"

ALTER TABLE "AFA     "."RCC_EXISTP" 
	ADD CONSTRAINT "RCC_EXISTP_PK" PRIMARY KEY
		("BJEDTE",
		 "BSPSQN");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_HDDZMX"
------------------------------------------------
DROP TABLE "AFA     "."RCC_HDDZMX";

CREATE TABLE "AFA     "."RCC_HDDZMX"  (
		  "SNDBNKCO" VARCHAR(10) NOT NULL , 
		  "TRCDAT" VARCHAR(8) NOT NULL , 
		  "TRCNO" VARCHAR(8) NOT NULL , 
		  "NCCWKDAT" VARCHAR(8) , 
		  "MSGTYPCO" VARCHAR(6) , 
		  "RCVMBRCO" VARCHAR(10) , 
		  "SNDMBRCO" VARCHAR(10) , 
		  "TRCCO" VARCHAR(7) , 
		  "SNDBRHCO" VARCHAR(6) , 
		  "SNDCLKNO" VARCHAR(8) , 
		  "SNDTRDAT" VARCHAR(8) , 
		  "SNDTRTIM" VARCHAR(6) , 
		  "MSGFLGNO" VARCHAR(26) , 
		  "ORMFN" VARCHAR(26) , 
		  "OPRTYPNO" VARCHAR(2) , 
		  "ROPRTPNO" VARCHAR(2) , 
		  "OPRSTNO" VARCHAR(3) , 
		  "SNDBNKNM" VARCHAR(60) , 
		  "RCVBNKCO" VARCHAR(10) , 
		  "RCVBNKNM" VARCHAR(60) , 
		  "CUR" VARCHAR(3) , 
		  "OCCAMT" DECIMAL(15,2) , 
		  "PYRACC" VARCHAR(32) , 
		  "PYRNAM" VARCHAR(60) , 
		  "PYRADDR" VARCHAR(60) , 
		  "PYEACC" VARCHAR(32) , 
		  "PYENAM" VARCHAR(60) , 
		  "PYEADDR" VARCHAR(60) , 
		  "OPRATTNO" VARCHAR(2) , 
		  "SEAL" VARCHAR(10) , 
		  "ORTRCCO" VARCHAR(7) , 
		  "ORSNDBNK" VARCHAR(10) , 
		  "ORRCVBNK" VARCHAR(10) , 
		  "ORTRCDAT" VARCHAR(8) , 
		  "ORTRCNO" VARCHAR(8) , 
		  "REMARK" VARCHAR(30) , 
		  "BILDAT" VARCHAR(8) , 
		  "BILNO" VARCHAR(8) , 
		  "BILTYP" VARCHAR(2) , 
		  "CPSAMT" DECIMAL(16,2) , 
		  "RFUAMT" DECIMAL(16,2) , 
		  "STRINFO" VARCHAR(60) , 
		  "USE" VARCHAR(20) , 
		  "BJEDTE" VARCHAR(8) , 
		  "BSPSQN" VARCHAR(12) , 
		  "BCSTAT" VARCHAR(2) , 
		  "BDWFLG" VARCHAR(1) , 
		  "EACTYP" VARCHAR(1) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."BCSTAT" IS '交易状态';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."BDWFLG" IS '流转处理标识';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."BILDAT" IS '票据日期';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."BILNO" IS '票据号码';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."BILTYP" IS '票据类型';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."BJEDTE" IS '报单日期';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."BSPSQN" IS '报单序号';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."CPSAMT" IS '赔偿金金额';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."CUR" IS '币种';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."EACTYP" IS '错账类型';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."MSGFLGNO" IS '报文标识号';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."MSGTYPCO" IS '报文标识号';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."OCCAMT" IS '交易金额';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."OPRATTNO" IS '业务属性';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."OPRSTNO" IS '业务状态';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."OPRTYPNO" IS '业务类型';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."ORMFN" IS '原报文标识号';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."ORRCVBNK" IS '原接收行号';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."ORSNDBNK" IS '原发送行号';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."ORTRCCO" IS '原交易代码';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."ORTRCDAT" IS '原交易代码';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."ORTRCNO" IS '原交易流水号';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."PYEACC" IS '收款人账号';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."PYEADDR" IS '收款人地址';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."PYENAM" IS '收款人户名';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."PYRACC" IS '付款人账号';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."PYRADDR" IS '付款人地址';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."PYRNAM" IS '付款人户名';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."RCVBNKCO" IS '接收行行号';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."RCVBNKNM" IS '接受行行名';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."RCVMBRCO" IS '接收成员行号';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."REMARK" IS '备注';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."RFUAMT" IS '拒付金金额';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."ROPRTPNO" IS '原业务类型';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."SEAL" IS '密押';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."SNDBNKCO" IS '发送行行号';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."SNDBNKNM" IS '发送行行名';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."SNDBRHCO" IS '发送机构号';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."SNDCLKNO" IS '发送柜员号';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."SNDMBRCO" IS '发送成员行号';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."SNDTRDAT" IS '发送交易日期';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."SNDTRTIM" IS '发送交易时间';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."STRINFO" IS '附言';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."TRCCO" IS '交易代码';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."TRCDAT" IS '委托日期';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."TRCNO" IS '交易流水号';

COMMENT ON COLUMN "AFA     "."RCC_HDDZMX"."USE" IS '用途';


-- DDL Statements for primary key on Table "AFA     "."RCC_HDDZMX"

ALTER TABLE "AFA     "."RCC_HDDZMX" 
	ADD CONSTRAINT "RCC_HDDZMX_PK" PRIMARY KEY
		("SNDBNKCO",
		 "TRCDAT",
		 "TRCNO");








------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_PJCBKA"
------------------------------------------------
DROP TABLE "AFA     "."RCC_PJCBKA";

CREATE TABLE "AFA     "."RCC_PJCBKA"  (
		  "BJEDTE" VARCHAR(8) NOT NULL , 
		  "BSPSQN" VARCHAR(12) NOT NULL , 
		  "BRSFLG" VARCHAR(1) NOT NULL , 
		  "BESBNO" VARCHAR(10) , 
		  "BETELR" VARCHAR(6) , 
		  "BEAUUS" VARCHAR(6) , 
		  "NCCWKDAT" VARCHAR(8) , 
		  "TRCCO" VARCHAR(7) , 
		  "TRCDAT" VARCHAR(8) , 
		  "TRCNO" VARCHAR(8) , 
		  "SNDMBRCO" VARCHAR(10) , 
		  "RCVMBRCO" VARCHAR(10) , 
		  "SNDBNKCO" VARCHAR(10) , 
		  "SNDBNKNM" VARCHAR(60) , 
		  "RCVBNKCO" VARCHAR(10) , 
		  "RCVBNKNM" VARCHAR(60) , 
		  "BOJEDT" VARCHAR(8) , 
		  "BOSPSQ" VARCHAR(12) , 
		  "ORTRCCO" VARCHAR(7) , 
		  "BILDAT" VARCHAR(8) , 
		  "BILNO" VARCHAR(8) , 
		  "BILPNAM" VARCHAR(60) , 
		  "BILENDDT" VARCHAR(8) , 
		  "BILAMT" DECIMAL(15,2) , 
		  "PYENAM" VARCHAR(60) , 
		  "HONBNKNM" VARCHAR(60) , 
		  "CONT" VARCHAR(255) , 
		  "ISDEAL" VARCHAR(1) , 
		  "PRCCO" VARCHAR(8) , 
		  "STRINFO" VARCHAR(60) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" ; 

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."BEAUUS" IS '授权柜员号';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."BESBNO" IS '机构号';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."BETELR" IS '柜员号';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."BILAMT" IS '出票金额';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."BILDAT" IS '票据日期';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."BILENDDT" IS '票据到期日';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."BILNO" IS '票据号码';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."BILPNAM" IS '出票人名称';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."BJEDTE" IS '报单日期';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."BOJEDT" IS '原报单日期';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."BOSPSQ" IS '原报单序号';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."BRSFLG" IS '往来标识(0-往账;1-来账)';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."BSPSQN" IS '报单序号';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."CONT" IS '内容';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."HONBNKNM" IS '承兑行名称';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."ISDEAL" IS '查复标识(0-未查复;1-已查复)';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."ORTRCCO" IS '原交易代码';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."PRCCO" IS '中心返回码';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."PYENAM" IS '收款人名称';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."RCVBNKCO" IS '接收行行号';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."RCVBNKNM" IS '接收行行名';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."RCVMBRCO" IS '接收成员行号';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."SNDBNKCO" IS '发送行行号';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."SNDBNKNM" IS '发送行行名';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."SNDMBRCO" IS '发送成员行号';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."STRINFO" IS '中心返回码说明';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."TRCCO" IS '交易代码';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."TRCDAT" IS '委托日期';

COMMENT ON COLUMN "AFA     "."RCC_PJCBKA"."TRCNO" IS '交易流水号';





------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_REKBAL"
------------------------------------------------
DROP TABLE "AFA     "."RCC_REKBAL";

CREATE TABLE "AFA     "."RCC_REKBAL"  (
		  "BJEDTE" VARCHAR(8) NOT NULL , 
		  "BSPSQN" VARCHAR(12) NOT NULL , 
		  "BRSFLG" VARCHAR(1) , 
		  "TRCCO" VARCHAR(7) , 
		  "NCCWKDAT" VARCHAR(8) , 
		  "TRCDAT" VARCHAR(8) , 
		  "TRCNO" VARCHAR(8) , 
		  "SNDMBRCO" VARCHAR(10) , 
		  "RCVMBRCO" VARCHAR(10) , 
		  "SNDBNKCO" VARCHAR(10) , 
		  "SNDBNKNM" VARCHAR(60) , 
		  "RCVBNKCO" VARCHAR(10) , 
		  "RCVBNKNM" VARCHAR(60) , 
		  "CUR" VARCHAR(3) , 
		  "LBDCFLG" VARCHAR(1) , 
		  "LSTDTBAL" DECIMAL(15,2) , 
		  "NTTDCFLG" VARCHAR(1) , 
		  "NTTBAL" DECIMAL(15,2) , 
		  "BALDCFLG" VARCHAR(1) , 
		  "TODAYBAL" DECIMAL(15,2) , 
		  "AVLBAL" DECIMAL(15,2) , 
		  "NTODAYBAL" DECIMAL(15,2) , 
		  "CHKRST" VARCHAR(1) , 
		  "BOJEDT" VARCHAR(8) , 
		  "BOSPSQ" VARCHAR(12) , 
		  "PRCCO" VARCHAR(8) , 
		  "STRINFO" VARCHAR(60) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."AVLBAL" IS '可用余额';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."BALDCFLG" IS '本日余额借方贷方标识';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."BJEDTE" IS '报单日期';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."BOJEDT" IS '原报单日期';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."BOSPSQ" IS '原报单序号';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."BRSFLG" IS '往来标识(0-往账;1-来账)';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."BSPSQN" IS '报单序号';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."CHKRST" IS '对账结果';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."CUR" IS '币种';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."LBDCFLG" IS '上日余额借方贷方标识';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."LSTDTBAL" IS '上日余额';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."NTODAYBAL" IS '行内今日余额';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."NTTBAL" IS '本日轧差额';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."NTTDCFLG" IS '本日轧差额借方贷方标识';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."PRCCO" IS '中心返回码';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."RCVBNKCO" IS '接受行行号';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."RCVBNKNM" IS '接受行行名';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."RCVMBRCO" IS '接收成员行号';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."SNDBNKCO" IS '发送行行号';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."SNDBNKNM" IS '发送行行名';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."SNDMBRCO" IS '发送成员行号';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."STRINFO" IS '中心返回码说明';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."TODAYBAL" IS '本日余额';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."TRCCO" IS '交易代码';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."TRCDAT" IS '委托日期';

COMMENT ON COLUMN "AFA     "."RCC_REKBAL"."TRCNO" IS '交易流水号';


-- DDL Statements for indexes on Table "AFA     "."RCC_REKBAL"

CREATE UNIQUE INDEX "AFA     "."RCC_REKBAL_IDX1" ON "AFA     "."RCC_REKBAL" 
		("TRCDAT" ASC,
		 "TRCNO" ASC,
		 "SNDBNKCO" ASC)
		PCTFREE 10 ALLOW REVERSE SCANS;


-- DDL Statements for primary key on Table "AFA     "."RCC_REKBAL"

ALTER TABLE "AFA     "."RCC_REKBAL" 
	ADD CONSTRAINT "RCC_REKBAL_PK" PRIMARY KEY
		("BJEDTE",
		 "BSPSQN");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_HDCBKA"
------------------------------------------------
DROP TABLE "AFA     "."RCC_HDCBKA";

CREATE TABLE "AFA     "."RCC_HDCBKA"  (
		  "BJEDTE" VARCHAR(8) NOT NULL , 
		  "BSPSQN" VARCHAR(12) NOT NULL , 
		  "BRSFLG" VARCHAR(1) NOT NULL , 
		  "BESBNO" VARCHAR(10) , 
		  "BETELR" VARCHAR(6) , 
		  "BEAUUS" VARCHAR(6) , 
		  "NCCWKDAT" VARCHAR(8) , 
		  "TRCCO" VARCHAR(7) , 
		  "TRCDAT" VARCHAR(8) , 
		  "TRCNO" VARCHAR(8) , 
		  "SNDMBRCO" VARCHAR(10) , 
		  "RCVMBRCO" VARCHAR(10) , 
		  "SNDBNKCO" VARCHAR(10) , 
		  "SNDBNKNM" VARCHAR(60) , 
		  "RCVBNKCO" VARCHAR(10) , 
		  "RCVBNKNM" VARCHAR(60) , 
		  "BOJEDT" VARCHAR(8) , 
		  "BOSPSQ" VARCHAR(12) , 
		  "ORTRCCO" VARCHAR(7) , 
		  "CUR" VARCHAR(3) , 
		  "OCCAMT" DECIMAL(15,2) , 
		  "CONT" VARCHAR(255) , 
		  "PYRACC" VARCHAR(32) , 
		  "PYRNAM" VARCHAR(60) , 
		  "PYEACC" VARCHAR(32) , 
		  "PYENAM" VARCHAR(60) , 
		  "ISDEAL" VARCHAR(1) , 
		  "PRCCO" VARCHAR(8) , 
		  "STRINFO" VARCHAR(60) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."BEAUUS" IS '授权柜员号';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."BESBNO" IS '机构号';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."BETELR" IS '柜员号';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."BJEDTE" IS '报单日期';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."BOJEDT" IS '原报单日期';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."BOSPSQ" IS '原报单序号';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."BRSFLG" IS '往来标识(0-往账;1-来账)';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."BSPSQN" IS '报单序号';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."CONT" IS '内容';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."CUR" IS '币种';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."ISDEAL" IS '查询查复标识(0-未查复;1-已查复)';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."OCCAMT" IS '交易金额';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."ORTRCCO" IS '原交易代码';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."PRCCO" IS '中心返回码';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."PYEACC" IS '收款人账号';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."PYENAM" IS '收款人户名';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."PYRACC" IS '付款人账号';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."PYRNAM" IS '付款人户名';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."RCVBNKCO" IS '接收行行号';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."RCVBNKNM" IS '接收行行名';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."RCVMBRCO" IS '接收成员行号';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."SNDBNKCO" IS '发送行行号';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."SNDBNKNM" IS '发送行行名';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."SNDMBRCO" IS '发送成员行号';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."STRINFO" IS '中心返回码说明';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."TRCCO" IS '交易代码';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."TRCDAT" IS '委托日期';

COMMENT ON COLUMN "AFA     "."RCC_HDCBKA"."TRCNO" IS '交易流水号';


-- DDL Statements for primary key on Table "AFA     "."RCC_HDCBKA"

ALTER TABLE "AFA     "."RCC_HDCBKA" 
	ADD CONSTRAINT "RCC_HDCBKA_PK" PRIMARY KEY
		("BJEDTE",
		 "BSPSQN");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_TRCBKA"
------------------------------------------------
DROP TABLE "AFA     "."RCC_TRCBKA";

CREATE TABLE "AFA     "."RCC_TRCBKA"  (
		  "BJEDTE" VARCHAR(8) NOT NULL , 
		  "BSPSQN" VARCHAR(12) NOT NULL , 
		  "BRSFLG" VARCHAR(1) NOT NULL , 
		  "BESBNO" VARCHAR(10) NOT NULL , 
		  "BEACSB" VARCHAR(10) , 
		  "BETELR" VARCHAR(6) NOT NULL , 
		  "BEAUUS" VARCHAR(6) , 
		  "TERMID" VARCHAR(20) , 
		  "BBSSRC" VARCHAR(1) NOT NULL , 
		  "DASQ" VARCHAR(10) , 
		  "DCFLG" VARCHAR(1) , 
		  "OPRNO" VARCHAR(2) , 
		  "OPRATTNO" VARCHAR(2) , 
		  "NCCWKDAT" VARCHAR(8) NOT NULL , 
		  "TRCCO" VARCHAR(7) NOT NULL , 
		  "TRCDAT" VARCHAR(8) NOT NULL , 
		  "TRCNO" VARCHAR(8) NOT NULL , 
		  "SNDMBRCO" VARCHAR(10) , 
		  "RCVMBRCO" VARCHAR(10) , 
		  "SNDBNKCO" VARCHAR(10) NOT NULL , 
		  "SNDBNKNM" VARCHAR(60) , 
		  "RCVBNKCO" VARCHAR(10) , 
		  "RCVBNKNM" VARCHAR(60) , 
		  "CUR" VARCHAR(3) NOT NULL , 
		  "OCCAMT" DECIMAL(15,2) NOT NULL , 
		  "CHRGTYP" VARCHAR(1) , 
		  "LOCCUSCHRG" DECIMAL(15,2) , 
		  "CUSCHRG" DECIMAL(15,2) , 
		  "PYRACC" VARCHAR(32) , 
		  "PYRNAM" VARCHAR(60) , 
		  "PYRADDR" VARCHAR(60) , 
		  "PYEACC" VARCHAR(32) , 
		  "PYENAM" VARCHAR(60) , 
		  "PYEADDR" VARCHAR(60) , 
		  "SEAL" VARCHAR(10) , 
		  "USE" VARCHAR(20) , 
		  "REMARK" VARCHAR(60) , 
		  "BILTYP" VARCHAR(2) , 
		  "BILDAT" VARCHAR(8) , 
		  "BILNO" VARCHAR(8) , 
		  "COMAMT" DECIMAL(15,2) , 
		  "OVPAYAMT" DECIMAL(15,2) , 
		  "CPSAMT" DECIMAL(15,2) , 
		  "RFUAMT" DECIMAL(15,2) , 
		  "CERTTYPE" VARCHAR(2) , 
		  "CERTNO" VARCHAR(20) , 
		  "BOJEDT" VARCHAR(8) , 
		  "BOSPSQ" VARCHAR(12) , 
		  "ORTRCDAT" VARCHAR(10) , 
		  "ORTRCCO" VARCHAR(7) , 
		  "ORTRCNO" VARCHAR(8) , 
		  "ORSNDBNK" VARCHAR(10) , 
		  "ORRCVBNK" VARCHAR(10) , 
		  "STRINFO" VARCHAR(60) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."BBSSRC" IS '资金来源';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."BEACSB" IS '账务机构号';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."BEAUUS" IS '授权柜员号';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."BESBNO" IS '机构号';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."BETELR" IS '柜员号';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."BILDAT" IS '票据日期';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."BILNO" IS '票据号码';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."BILTYP" IS '票据类型';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."BJEDTE" IS '报单日期';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."BOJEDT" IS '原报单日期';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."BOSPSQ" IS '原报单序号';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."BRSFLG" IS '往来标识(0-往账;1-来账)';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."BSPSQN" IS '报单序号';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."CERTNO" IS '证件号码';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."CERTTYPE" IS '证件种类';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."CHRGTYP" IS '手续费收取方式';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."COMAMT" IS '原托收金额';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."CPSAMT" IS '赔偿金金额';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."CUR" IS '币种';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."CUSCHRG" IS '异地客户手续费';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."DASQ" IS '销账序号';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."DCFLG" IS '借贷标识(1-借;2-贷)';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."LOCCUSCHRG" IS '本地客户手续费';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."OCCAMT" IS '交易金额';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."OPRATTNO" IS '业务属性';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."OPRNO" IS '业务种类';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."ORRCVBNK" IS '原接收行号';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."ORSNDBNK" IS '原发送行号';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."ORTRCCO" IS '原交易代码';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."ORTRCDAT" IS '原委托日期';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."ORTRCNO" IS '原交易流水号';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."OVPAYAMT" IS '多付金额';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."PYEACC" IS '收款人账号';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."PYEADDR" IS '收款人地址';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."PYENAM" IS '收款人户名';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."PYRACC" IS '付款人账号';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."PYRADDR" IS '付款人地址';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."PYRNAM" IS '付款人户名';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."RCVBNKCO" IS '接收行行号';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."RCVBNKNM" IS '接收行行名';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."RCVMBRCO" IS '接收成员行号';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."REMARK" IS '备注';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."RFUAMT" IS '拒付金额';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."SEAL" IS '密押';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."SNDBNKCO" IS '发送行行号';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."SNDBNKNM" IS '发送行行名';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."SNDMBRCO" IS '发送成员行号';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."STRINFO" IS '附言';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."TERMID" IS '终端号';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."TRCCO" IS '交易代码';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."TRCDAT" IS '委托日期';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."TRCNO" IS '交易流水号';

COMMENT ON COLUMN "AFA     "."RCC_TRCBKA"."USE" IS '用途';


-- DDL Statements for primary key on Table "AFA     "."RCC_TRCBKA"

ALTER TABLE "AFA     "."RCC_TRCBKA" 
	ADD CONSTRAINT "RCC_TRCBKA_PK" PRIMARY KEY
		("BJEDTE",
		 "BSPSQN");


-- DDL Statements for unique constraints on Table "AFA     "."RCC_TRCBKA"


ALTER TABLE "AFA     "."RCC_TRCBKA" 
	ADD UNIQUE
		("TRCDAT",
		 "TRCNO",
		 "SNDBNKCO");

------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_BILBKA"
------------------------------------------------
DROP TABLE "AFA     "."RCC_BILBKA";

CREATE TABLE "AFA     "."RCC_BILBKA"  (
		  "BJEDTE" VARCHAR(8) NOT NULL , 
		  "BSPSQN" VARCHAR(12) NOT NULL , 
		  "BRSFLG" VARCHAR(1) NOT NULL , 
		  "BESBNO" VARCHAR(10) , 
		  "BEACSB" VARCHAR(10) , 
		  "BETELR" VARCHAR(6) , 
		  "BEAUUS" VARCHAR(6) , 
		  "TERMID" VARCHAR(20) NOT NULL , 
		  "BBSSRC" VARCHAR(1) NOT NULL , 
		  "DASQ" VARCHAR(10) , 
		  "DCFLG" VARCHAR(1) , 
		  "OPRNO" VARCHAR(2) , 
		  "OPRATTNO" VARCHAR(2) , 
		  "NCCWKDAT" VARCHAR(8) , 
		  "TRCCO" VARCHAR(7) , 
		  "TRCDAT" VARCHAR(8) NOT NULL , 
		  "TRCNO" VARCHAR(8) NOT NULL , 
		  "SNDMBRCO" VARCHAR(10) , 
		  "RCVMBRCO" VARCHAR(10) , 
		  "SNDBNKCO" VARCHAR(10) NOT NULL , 
		  "SNDBNKNM" VARCHAR(60) , 
		  "RCVBNKCO" VARCHAR(10) , 
		  "RCVBNKNM" VARCHAR(60) , 
		  "BILVER" VARCHAR(2) , 
		  "BILNO" VARCHAR(8) , 
		  "CHRGTYP" VARCHAR(1) , 
		  "LOCCUSCHRG" DECIMAL(15,2) , 
		  "BILRS" VARCHAR(1) , 
		  "HPCUSQ" SMALLINT NOT NULL , 
		  "HPSTAT" VARCHAR(2) , 
		  "CERTTYPE" VARCHAR(2) , 
		  "CERTNO" VARCHAR(20) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."BBSSRC" IS '资金来源';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."BEACSB" IS '账务机构号';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."BEAUUS" IS '授权柜员号';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."BESBNO" IS '机构号';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."BETELR" IS '柜员号';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."BILNO" IS '汇票号码';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."BILRS" IS '汇票本行他行标识(0-本行签发的汇票;1-他行签发的汇票)';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."BILVER" IS '汇票版本号';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."BJEDTE" IS '报单日期';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."BRSFLG" IS '往来标识(0-往账;1-来账)';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."BSPSQN" IS '报单序号';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."CERTNO" IS '证件号码';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."CERTTYPE" IS '证件类型';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."CHRGTYP" IS '手续费收取方式';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."DASQ" IS '销账序号';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."DCFLG" IS '借贷标识(1-借;2-贷)';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."HPCUSQ" IS '汇票状态编号';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."HPSTAT" IS '汇票状态';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."LOCCUSCHRG" IS '手续费';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."OPRATTNO" IS '业务属性';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."OPRNO" IS '业务种类';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."RCVBNKCO" IS '接受行行号';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."RCVBNKNM" IS '接受行行名';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."RCVMBRCO" IS '接收成员行号';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."SNDBNKCO" IS '发送行行号';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."SNDBNKNM" IS '发送行行名';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."SNDMBRCO" IS '发送成员行号';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."TERMID" IS '终端号';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."TRCCO" IS '交易代码';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."TRCDAT" IS '交易日期';

COMMENT ON COLUMN "AFA     "."RCC_BILBKA"."TRCNO" IS '交易流水号';


-- DDL Statements for primary key on Table "AFA     "."RCC_BILBKA"

ALTER TABLE "AFA     "."RCC_BILBKA" 
	ADD CONSTRAINT "RCC_BILBKA_PK" PRIMARY KEY
		("BJEDTE",
		 "BSPSQN");


-- DDL Statements for unique constraints on Table "AFA     "."RCC_BILBKA"


ALTER TABLE "AFA     "."RCC_BILBKA" 
	ADD UNIQUE
		("TRCDAT",
		 "TRCNO",
		 "SNDBNKCO");

------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_ZTCBKA"
------------------------------------------------
DROP TABLE "AFA     "."RCC_ZTCBKA";

CREATE TABLE "AFA     "."RCC_ZTCBKA"  (
		  "BJEDTE" VARCHAR(8) NOT NULL , 
		  "BSPSQN" VARCHAR(12) NOT NULL , 
		  "BRSFLG" VARCHAR(1) NOT NULL , 
		  "BESBNO" VARCHAR(10) , 
		  "BEACSB" VARCHAR(10) , 
		  "BETELR" VARCHAR(6) , 
		  "BEAUUS" VARCHAR(6) , 
		  "NCCWKDAT" VARCHAR(8) , 
		  "TRCCO" VARCHAR(7) , 
		  "TRCDAT" VARCHAR(8) , 
		  "TRCNO" VARCHAR(8) , 
		  "SNDMBRCO" VARCHAR(10) , 
		  "RCVMBRCO" VARCHAR(10) , 
		  "SNDBNKCO" VARCHAR(10) , 
		  "SNDBNKNM" VARCHAR(60) , 
		  "RCVBNKCO" VARCHAR(10) , 
		  "RCVBNKNM" VARCHAR(60) , 
		  "BOJEDT" VARCHAR(8) , 
		  "BOSPSQ" VARCHAR(12) , 
		  "ORTRCCO" VARCHAR(7) , 
		  "CUR" VARCHAR(3) , 
		  "OCCAMT" DECIMAL(15,2) , 
		  "CONT" VARCHAR(255) , 
		  "NCCTRCST" VARCHAR(2) , 
		  "MBRTRCST" VARCHAR(2) , 
		  "ISDEAL" VARCHAR(1) , 
		  "PRCCO" VARCHAR(8) , 
		  "STRINFO" VARCHAR(60) , 
		  "NOTE1" VARCHAR(10) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."BEACSB" IS '财务机构号';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."BEAUUS" IS '授权柜员号';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."BESBNO" IS '机构号';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."BETELR" IS '柜员号';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."BJEDTE" IS '报单日期';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."BOJEDT" IS '原报单日期';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."BOSPSQ" IS '原报单序号';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."BRSFLG" IS '往来标识(0-往账;1-来账)';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."BSPSQN" IS '报单序号';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."CONT" IS '内容';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."CUR" IS '币种';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."ISDEAL" IS '查复标识(0-未查复;1-已查复)';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."MBRTRCST" IS '成员行交易状态';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."NCCTRCST" IS '中心交易状态';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."NCCWKDAT" IS '中心日期';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."OCCAMT" IS '交易金额';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."ORTRCCO" IS '原交易代码';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."PRCCO" IS '中心返回码';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."RCVBNKCO" IS '接收行行号';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."RCVBNKNM" IS '接收行行名';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."RCVMBRCO" IS '接收成员行号';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."SNDBNKCO" IS '发送行行号';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."SNDBNKNM" IS '发送行行名';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."SNDMBRCO" IS '发送成员行号';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."STRINFO" IS '中心返回码说明';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."TRCCO" IS '交易代码';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."TRCDAT" IS '委托日期';

COMMENT ON COLUMN "AFA     "."RCC_ZTCBKA"."TRCNO" IS '交易流水号';


-- DDL Statements for primary key on Table "AFA     "."RCC_ZTCBKA"

ALTER TABLE "AFA     "."RCC_ZTCBKA" 
	ADD CONSTRAINT "RCC_ZTCBKA_PK" PRIMARY KEY
		("BJEDTE",
		 "BSPSQN",
		 "BRSFLG");


------------------------------------------------
-- DDL Statements for table "AFA     "."RCC_QSQHQD"
------------------------------------------------
DROP TABLE "AFA     "."RCC_QSQHQD";

CREATE TABLE "AFA     "."RCC_QSQHQD"  (
		  "STRDAT" VARCHAR(8) NOT NULL , 
		  "ENDDAT" VARCHAR(8) NOT NULL , 
		  "BESBNO" VARCHAR(10) NOT NULL , 
		  "BESBNM" VARCHAR(60) , 
		  "TRCCHRGCNT" SMALLINT NOT NULL , 
		  "TRCCHRGAMT" DECIMAL(15,2) , 
		  "BILCHRGCNT" SMALLINT NOT NULL , 
		  "BILCHRGAMT" DECIMAL(15,2) , 
		  "UCSWCHRGCNT" SMALLINT NOT NULL , 
		  "UCSWCHRGAMT" DECIMAL(15,2) , 
		  "TCNT" SMALLINT NOT NULL , 
		  "TAMT" DECIMAL(15,2) , 
		  "ISDEAL" VARCHAR(1) , 
		  "FEDT" VARCHAR(8) , 
		  "RBSQ" VARCHAR(12) , 
		  "TRDT" VARCHAR(8) , 
		  "TLSQ" VARCHAR(10) , 
		  "MGID" VARCHAR(7) , 
		  "STRINFO" VARCHAR(60) , 
		  "NOTE1" VARCHAR(20) , 
		  "NOTE2" VARCHAR(20) , 
		  "NOTE3" VARCHAR(60) , 
		  "NOTE4" VARCHAR(60) )   
		 IN "AFA_DATA" INDEX IN "AFA_IDX" ; 

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."BESBNM" IS '机构名称';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."BESBNO" IS '机构号';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."BILCHRGAMT" IS '全国汇票手续费总金额';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."BILCHRGCNT" IS '全国汇票手续费总笔数';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."ENDDAT" IS '结束日期';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."FEDT" IS '前置日期';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."ISDEAL" IS '处理标识(0-未处理;1-已处理)';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."MGID" IS '主机返回码';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."NOTE1" IS '附加字段1';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."NOTE2" IS '附加字段2';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."NOTE3" IS '附加字段3';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."NOTE4" IS '附加字段4';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."RBSQ" IS '前置流水号';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."STRDAT" IS '起始日期';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."STRINFO" IS '返回码说明';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."TAMT" IS '汇总金额';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."TCNT" IS '汇总笔数';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."TLSQ" IS '主机流水号';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."TRCCHRGAMT" IS '实时汇兑手续费总金额';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."TRCCHRGCNT" IS '实时汇兑手续费总笔数';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."TRDT" IS '主机日期';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."UCSWCHRGAMT" IS '通存通兑手续费总金额';

COMMENT ON COLUMN "AFA     "."RCC_QSQHQD"."UCSWCHRGCNT" IS '通存通兑手续费总笔数';


-- DDL Statements for primary key on Table "AFA     "."RCC_QSQHQD"

ALTER TABLE "AFA     "."RCC_QSQHQD" 
	ADD CONSTRAINT "RCC_QSQHQD_PK" PRIMARY KEY
		("STRDAT",
		 "ENDDAT",
		 "BESBNO");








COMMIT WORK;

CONNECT RESET;

TERMINATE;

