---------------------------------------
--数据移行脚步
--作者:刘雨龙
--时间:2008-08-02
--功能:从原有生成环境数据库数据移行到新
--     平台数据库内
---------------------------------------

CONNECT TO MAPS;


---------------------------------------
--平台数据移行
---------------------------------------

IMPORT FROM SUMMARY.del OF DEL INSERT INTO AFA_SUMMARY;

IMPORT FROM CRONADM.del OF DEL INSERT INTO AFA_CRONADM;

---------------------------------------
--从测试机193移行数据
--将测试机导出数据与此脚步放置同一目录
---------------------------------------

IMPORT FROM RESPCODE.del OF DEL INSERT INTO AFA_RESPCODE;

---------------------------------------
--批量业务数据移行
---------------------------------------

IMPORT FROM BUSIINFO.del OF DEL INSERT INTO ABDT_UNITINFO;

IMPORT FROM CUSTINFO.del OF DEL INSERT INTO ABDT_CUSTINFO;

IMPORT FROM BATCHINFO.del OF DEL INSERT INTO ABDT_BATCHINFO;

IMPORT FROM HISBUSIINFO.del OF DEL INSERT INTO ABDT_HIS_UNITINFO;

IMPORT FROM HISCUSTINFO.del OF DEL INSERT INTO ABDT_HIS_CUSTINFO;

IMPORT FROM HISBATCHINFO.del OF DEL INSERT INTO ABDT_HIS_BATCHINFO;

IMPORT FROM CZDZB.del OF DEL INSERT INTO ABDT_CZDZB;

---------------------------------------
--非税业务数据移行
---------------------------------------

IMPORT FROM AA11.del OF DEL INSERT INTO FS_AA1;

IMPORT FROM BUSINOCONF.del OF DEL INSERT INTO FS_BUSINOCONF;

IMPORT FROM BUSINOINFO.del OF DEL INSERT INTO FS_BUSINOINFO;

IMPORT FROM DETAIL.del OF DEL INSERT INTO FS_DETAIL;

IMPORT FROM DPZGL.del OF DEL INSERT INTO FS_DPZ_GL;

IMPORT FROM FA13.del OF DEL INSERT INTO FS_FA13;

IMPORT FROM FA15.del OF DEL INSERT INTO FS_FA15;

IMPORT FROM FA16.del OF DEL INSERT INTO FS_FA16;

IMPORT FROM FA20.del OF DEL INSERT INTO FS_FA20;

IMPORT FROM FA21.del OF DEL INSERT INTO FS_FA21;

IMPORT FROM FA22.del OF DEL INSERT INTO FS_FA22;

IMPORT FROM FC06.del OF DEL INSERT INTO FS_FC06;

IMPORT FROM FC60.del OF DEL INSERT INTO FS_FC60;

IMPORT FROM FC70.del OF DEL INSERT INTO FS_FC70;

IMPORT FROM FC74.del OF DEL INSERT INTO FS_FC74;

IMPORT FROM FC74OUT.del OF DEL INSERT INTO FS_FC74_OUT;

IMPORT FROM FC75.del OF DEL INSERT INTO FS_FC75;

IMPORT FROM FC76.del OF DEL INSERT INTO FS_FC76;

IMPORT FROM FC76OUT.del OF DEL INSERT INTO FS_FC76_OUT;

IMPORT FROM FC84.del OF DEL INSERT INTO FS_FC84;

IMPORT FROM REMAIN.del OF DEL INSERT INTO FS_REMAIN;

IMPORT FROM MAINTRANSDTL.del OF DEL INSERT INTO FS_MAINTRANSDTL;

----------------------------------
--数据提交
----------------------------------

COMMIT WORK;

CONNECT RESET;

TERMINATE;