--
--ER/Studio 7.0 SQL Code Generation
-- Company :      agree
-- Project :      Model_TIPS.DM1
-- Author :       zeng
--
-- Date Created : Monday, September 08, 2008 16:29:35
-- Target DBMS : IBM DB2 UDB 8.x
--
connect to maps;

DROP TABLE TIPS_ADM
;
DROP TABLE TIPS_BANKCODE
;
DROP TABLE TIPS_BANKCODEDTL
;
DROP TABLE TIPS_BATCHADM
;
DROP TABLE TIPS_BATCHDATA
;
DROP TABLE TIPS_BRANCH_ADM
;
DROP TABLE TIPS_BUDGETSUBJECTCODE
;
DROP TABLE TIPS_BUDGETSUBJECTCODEDTL
;
DROP TABLE TIPS_CHECKADM
;
DROP TABLE TIPS_CHECKDATA
;
DROP TABLE TIPS_CUSTINFO
;
DROP TABLE TIPS_LIQUIDATE_ADM
;
DROP TABLE TIPS_LOG
;
DROP TABLE TIPS_MAINTRANSDTL
;
DROP TABLE TIPS_NODECODE
;
DROP TABLE TIPS_NODECODEDTL
;
DROP TABLE TIPS_NOTE
;
DROP TABLE TIPS_RUNPARAM
;
DROP TABLE TIPS_TAXCODE
;
DROP TABLE TIPS_TAXCODEDTL
;
DROP TABLE TIPS_TAXSUBJECTCODE
;
DROP TABLE TIPS_TAXSUBJECTCODEDTL
;
DROP TABLE TIPS_TAXTYPECODE
;
DROP TABLE TIPS_TAXTYPECODEDTL
;
DROP TABLE TIPS_TRECODE
;
DROP TABLE TIPS_TRECODEDTL
;
DROP TABLE TIPS_VOU_TAXTYPE
;
-- 
-- TABLE: TIPS_ADM 
--

CREATE TABLE TIPS_ADM(
    WORKDATE    VARCHAR(8),
    STATUS      VARCHAR(1)     NOT NULL,
    NOTE1       VARCHAR(10),
    NOTE2       VARCHAR(20),
    NOTE3       VARCHAR(60),
    NOTE4       VARCHAR(60),
    NOTE5       VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_BANKCODE 
--

CREATE TABLE TIPS_BANKCODE(
    RECKBANKNO      VARCHAR(12)    NOT NULL,
    GENBANKNAME     VARCHAR(60),
    RECKONTYPE      VARCHAR(1),
    OFNODECODE      VARCHAR(12),
    ADDRESS         VARCHAR(80),
    POSTALCODE      VARCHAR(6),
    PEOPLENAME      VARCHAR(10),
    PEOPLEPHONE     VARCHAR(15),
    PEOPLEMOBILE    VARCHAR(11),
    EMAIL           VARCHAR(60),
    STATUS          VARCHAR(1),
    EFFECTDATE      VARCHAR(8),
    UPDATEAREA      VARCHAR(10),
    UPDATEBATCH     VARCHAR(8),
    NOTE1           VARCHAR(10),
    NOTE2           VARCHAR(20),
    NOTE3           VARCHAR(60),
    NOTE4           VARCHAR(60),
    NOTE5           VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_BANKCODEDTL 
--

CREATE TABLE TIPS_BANKCODEDTL(
    RECKBANKNO      VARCHAR(12)    NOT NULL,
    OPERSIGN        VARCHAR(1)     NOT NULL,
    GENBANKNAME     VARCHAR(60),
    RECKONTYPE      VARCHAR(1),
    OFNODECODE      VARCHAR(12),
    ADDRESS         VARCHAR(80),
    POSTALCODE      VARCHAR(6),
    PEOPLENAME      VARCHAR(10),
    PEOPLEPHONE     VARCHAR(15),
    PEOPLEMOBILE    VARCHAR(11),
    EMAIL           VARCHAR(60),
    STATUS          VARCHAR(1),
    EFFECTDATE      VARCHAR(8),
    UPDATEAREA      VARCHAR(10),
    UPDATEBATCH     VARCHAR(8),
    NOTE1           VARCHAR(10),
    NOTE2           VARCHAR(20),
    NOTE3           VARCHAR(60),
    NOTE4           VARCHAR(60),
    NOTE5           VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_BATCHADM 
--

CREATE TABLE TIPS_BATCHADM(
    WORKDATE       VARCHAR(8)     NOT NULL,
    BATCHNO        VARCHAR(20)    NOT NULL,
    TAXORGCODE     VARCHAR(12)    NOT NULL,
    PAYEEBANKNO    VARCHAR(12),
    PAYEEACCT      VARCHAR(32),
    PAYEENAME      VARCHAR(60),
    PAYBKCODE      VARCHAR(12),
    RETURNTERM     VARCHAR(8),
    WORKTIME       VARCHAR(8),
    DEALSTATUS     VARCHAR(1)     NOT NULL,
    ERRORCODE      VARCHAR(10),
    ERRORMSG       VARCHAR(60),
    TOTALNUM       VARCHAR(20),
    TOTALAMT       VARCHAR(20),
    SUCCNUM        VARCHAR(20),
    SUCCAMT        VARCHAR(20),
    NOTE1          VARCHAR(20),
    NOTE2          VARCHAR(20),
    NOTE3          VARCHAR(40),
    NOTE4          VARCHAR(40),
    NOTE5          VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_BATCHDATA 
--

CREATE TABLE TIPS_BATCHDATA(
    WORKDATE        VARCHAR(8)       NOT NULL,
    BATCHNO         VARCHAR(20)      NOT NULL,
    TAXORGCODE      VARCHAR(12)      NOT NULL,
    SERIALNO        VARCHAR(20)      NOT NULL,
    DEALDATE        VARCHAR(8),
    DEALTIME        VARCHAR(6),
    CORPSERIALNO    VARCHAR(20)      NOT NULL,
    ACCNO           VARCHAR(30),
    PayOpBkCode     CHAR(10),
    TAXPAYCODE      VARCHAR(30)      NOT NULL,
    HandOrgName     CHAR(10),
    AMOUNT          VARCHAR(17)      NOT NULL,
    STATUS          VARCHAR(1)       NOT NULL,
    ERRORCODE       VARCHAR(10),
    ERRORMSG        VARCHAR(60),
    NOTE1           VARCHAR(20),
    NOTE2           VARCHAR(20),
    NOTE3           VARCHAR(40),
    NOTE4           VARCHAR(40),
    NOTE5           VARCHAR(60),
    NOTE6           VARCHAR(60),
    NOTE7           VARCHAR(80),
    NOTE8           VARCHAR(80),
    NOTE9           VARCHAR(100),
    NOTE10          VARCHAR(2048)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_BRANCH_ADM 
--

CREATE TABLE TIPS_BRANCH_ADM(
    BRNO           VARCHAR(10)    NOT NULL,
    PAYBKCODE      VARCHAR(12)    NOT NULL,
    BANKNO         VARCHAR(16),
    BANKACCT       VARCHAR(32),
    BANKNAME       VARCHAR(60),
    PAYEEBANKNO    VARCHAR(12)    NOT NULL,
    STATUS         VARCHAR(1)     NOT NULL,
    ACCNO          VARCHAR(25)    NOT NULL,
    NOTE1          VARCHAR(20),
    NOTE2          VARCHAR(40),
    NOTE3          VARCHAR(60),
    NOTE4          VARCHAR(60),
    NOTE5          VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_BUDGETSUBJECTCODE 
--

CREATE TABLE TIPS_BUDGETSUBJECTCODE(
    BUDGETSUBJECTCODE    VARCHAR(30)    NOT NULL,
    SUBJECTTYPE          VARCHAR(1)     NOT NULL,
    IESIGN               VARCHAR(12)    NOT NULL,
    UPDATEAREA           VARCHAR(10)    NOT NULL,
    BUDGETSUBJECTNAME    VARCHAR(60),
    BUDGETATTRIB         VARCHAR(10),
    STATUS               VARCHAR(1),
    EFFECTDATE           VARCHAR(8),
    UPDATEBATCH          VARCHAR(8),
    NOTE1                VARCHAR(10),
    NOTE2                VARCHAR(20),
    NOTE3                VARCHAR(60),
    NOTE4                VARCHAR(60),
    NOTE5                VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_BUDGETSUBJECTCODEDTL 
--

CREATE TABLE TIPS_BUDGETSUBJECTCODEDTL(
    BUDGETSUBJECTCODE    VARCHAR(30)    NOT NULL,
    SUBJECTTYPE          VARCHAR(1)     NOT NULL,
    IESIGN               VARCHAR(12)    NOT NULL,
    UPDATEAREA           VARCHAR(10)    NOT NULL,
    OPERSIGN             VARCHAR(1)     NOT NULL,
    BUDGETSUBJECTNAME    VARCHAR(60),
    BUDGETATTRIB         VARCHAR(10),
    STATUS               VARCHAR(1),
    EFFECTDATE           VARCHAR(8),
    UPDATEBATCH          VARCHAR(8),
    NOTE1                VARCHAR(10),
    NOTE2                VARCHAR(20),
    NOTE3                VARCHAR(60),
    NOTE4                VARCHAR(60),
    NOTE5                VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_CHECKADM 
--

CREATE TABLE TIPS_CHECKADM(
    WORKDATE           VARCHAR(8)     NOT NULL,
    BATCHNO            VARCHAR(20)    NOT NULL,
    PAYBKCODE          VARCHAR(12)    NOT NULL,
    PAYEEBANKNO        VARCHAR(12)    NOT NULL,
    CHKACCTTYPE        VARCHAR(1),
    PRIORCHKACCTORD    CHAR(10),
    WORKTIME           VARCHAR(8),
    DEALSTATUS         VARCHAR(1)     NOT NULL,
    TOTALNUM           VARCHAR(20),
    TOTALAMT           VARCHAR(20),
    SUCCNUM            VARCHAR(20),
    SUCCAMT            VARCHAR(20),
    ERRORCODE          VARCHAR(10),
    ERRORMSG           VARCHAR(60),
    NOTE1              VARCHAR(20),
    NOTE2              VARCHAR(20),
    NOTE3              VARCHAR(40),
    NOTE4              VARCHAR(40),
    NOTE5              VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_CHECKDATA 
--

CREATE TABLE TIPS_CHECKDATA(
    WORKDATE        VARCHAR(8)      NOT NULL,
    BATCHNO         VARCHAR(20)     NOT NULL,
    CORPSERIALNO    VARCHAR(20)     NOT NULL,
    PAYBKCODE       VARCHAR(12)     NOT NULL,
    PAYEEBANKNO     VARCHAR(12)     NOT NULL,
    TAXVOUNO        VARCHAR(18),
    ACCNO           VARCHAR(30),
    AMOUNT          VARCHAR(17)     NOT NULL,
    STATUS          VARCHAR(1)      NOT NULL,
    ERRORCODE       VARCHAR(10),
    ERRORMSG        VARCHAR(40),
    NOTE1           VARCHAR(20),
    NOTE2           VARCHAR(20),
    NOTE3           VARCHAR(40),
    NOTE4           VARCHAR(40),
    NOTE5           VARCHAR(60),
    NOTE6           VARCHAR(60),
    NOTE7           VARCHAR(80),
    NOTE8           VARCHAR(80),
    NOTE9           VARCHAR(100),
    NOTE10          VARCHAR(100)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_CUSTINFO 
--

CREATE TABLE TIPS_CUSTINFO(
    PAYACCT        VARCHAR(23)     NOT NULL,
    TAXORGCODE     VARCHAR(12)     NOT NULL,
    TAXPAYCODE     VARCHAR(20)     NOT NULL,
    PROTOCOLNO     VARCHAR(60)     NOT NULL,
    TAXPAYNAME     VARCHAR(200),
    PAYOPBKCODE    VARCHAR(12)     NOT NULL,
    HANDORGNAME    VARCHAR(200),
    IDTYPE         VARCHAR(2),
    IDCODE         VARCHAR(20),
    STARTDATE      VARCHAR(8),
    ENDDATE        VARCHAR(8),
    STATUS         VARCHAR(1)      NOT NULL,
    ZONENO         VARCHAR(10),
    BRNO           VARCHAR(10),
    TELLERNO       VARCHAR(10),
    WORKDATE       VARCHAR(8)      NOT NULL,
    NOTE1          VARCHAR(10),
    NOTE2          VARCHAR(20),
    NOTE3          VARCHAR(30),
    NOTE4          VARCHAR(40),
    NOTE5          VARCHAR(50)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_LIQUIDATE_ADM 
--

CREATE TABLE TIPS_LIQUIDATE_ADM(
    PAYBKCODE        VARCHAR(12)    NOT NULL,
    PAYEEBANKNO      VARCHAR(12)    NOT NULL,
    TRECODE          VARCHAR(12)    NOT NULL,
    TRENAME          VARCHAR(60),
    PAYEEACCT        VARCHAR(25)    NOT NULL,
    PAYEEACCTNAME    VARCHAR(60),
    PAYBKNAME        VARCHAR(60),
    BRNO             VARCHAR(10)    NOT NULL,
    TELLERNO         VARCHAR(10)    NOT NULL,
    STATUS           VARCHAR(1)     NOT NULL,
    LIQUIDATEMODE    VARCHAR(1)     NOT NULL,
    NOTE1            VARCHAR(20),
    NOTE2            VARCHAR(20),
    NOTE3            VARCHAR(60),
    NOTE4            VARCHAR(60),
    NOTE5            VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_LOG 
--

CREATE TABLE TIPS_LOG(
    WORKDATE    VARCHAR(8),
    WORKTIME    VARCHAR(6),
    TRXCODE     VARCHAR(10),
    NOTE1       VARCHAR(10),
    NOTE2       VARCHAR(20),
    NOTE3       VARCHAR(60),
    NOTE4       VARCHAR(100),
    NOTE5       VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_MAINTRANSDTL 
--

CREATE TABLE TIPS_MAINTRANSDTL(
    SERIALNO        VARCHAR(8)      NOT NULL,
    WORKDATE        VARCHAR(8)      NOT NULL,
    WORKTIME        VARCHAR(6)      NOT NULL,
    TRXCODE         VARCHAR(10),
    BRNO            VARCHAR(10)     NOT NULL,
    ZONENO          VARCHAR(10)     NOT NULL,
    TELLERNO        VARCHAR(10)     NOT NULL,
    AUTHTELLERNO    VARCHAR(10),
    TERMID          VARCHAR(20),
    CHANNELCODE     VARCHAR(3),
    TRADETYPE       VARCHAR(3),
    CATRFLAG        VARCHAR(1),
    DRACCNO         VARCHAR(25)     NOT NULL,
    CRACCNO         VARCHAR(25),
    VOUHTYPE        VARCHAR(3),
    VOUHNO          VARCHAR(20),
    TAXVOUNO        VARCHAR(18),
    TAXPAYCODE      VARCHAR(20)     NOT NULL,
    TAXPAYNAME      VARCHAR(60),
    AMOUNT          VARCHAR(17)     NOT NULL,
    REVTRANF        VARCHAR(1)      NOT NULL,
    PRESERNO        VARCHAR(8),
    BANKSTATUS      VARCHAR(1),
    BANKCODE        VARCHAR(10),
    BANKSERNO       VARCHAR(20),
    CORPSTATUS      VARCHAR(1),
    CORPCODE        VARCHAR(10),
    CORPSERNO       VARCHAR(20),
    CORPTIME        VARCHAR(20),
    ERRORMSG        VARCHAR(100),
    CHKFLAG         VARCHAR(1),
    CORPCHKFLAG     VARCHAR(1),
    NOTE1           VARCHAR(20),
    NOTE2           VARCHAR(20),
    NOTE3           VARCHAR(40),
    NOTE4           VARCHAR(40),
    NOTE5           VARCHAR(40),
    NOTE6           VARCHAR(40),
    NOTE7           VARCHAR(40),
    NOTE8           VARCHAR(40),
    NOTE9           VARCHAR(60),
    NOTE10          VARCHAR(100)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_NODECODE 
--

CREATE TABLE TIPS_NODECODE(
    NODECODE       VARCHAR(12)     NOT NULL,
    NODENAME       VARCHAR(60),
    OFNODETYPE     VARCHAR(1),
    NODEDN         VARCHAR(150),
    STATUS         VARCHAR(1),
    RUNSTATUS      VARCHAR(1),
    EFFECTDATE     VARCHAR(8),
    UPDATEAREA     VARCHAR(10),
    UPDATEBATCH    VARCHAR(8),
    NOTE1          VARCHAR(10),
    NOTE2          VARCHAR(20),
    NOTE3          VARCHAR(60),
    NOTE4          VARCHAR(60),
    NOTE5          VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_NODECODEDTL 
--

CREATE TABLE TIPS_NODECODEDTL(
    NODECODE       VARCHAR(12)     NOT NULL,
    OPERSIGN       VARCHAR(1)      NOT NULL,
    NODENAME       VARCHAR(60),
    OFNODETYPE     VARCHAR(1),
    NODEDN         VARCHAR(150),
    STATUS         VARCHAR(1),
    RUNSTATUS      VARCHAR(1),
    EFFECTDATE     VARCHAR(8),
    UPDATEAREA     VARCHAR(10),
    UPDATEBATCH    VARCHAR(8),
    NOTE1          VARCHAR(10),
    NOTE2          VARCHAR(20),
    NOTE3          VARCHAR(60),
    NOTE4          VARCHAR(60),
    NOTE5          VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_NOTE 
--

CREATE TABLE TIPS_NOTE(
    WORKDATE       VARCHAR(8)       NOT NULL,
    WORKTIME       VARCHAR(6)       NOT NULL,
    SRCNODECODE    VARCHAR(12),
    DESNODECODE    VARCHAR(12),
    SENDORGCODE    VARCHAR(12),
    RCVORGCODE     VARCHAR(12),
    CONTENT        VARCHAR(2048),
    NOTE1          VARCHAR(20),
    NOTE2          VARCHAR(20),
    NOTE3          VARCHAR(60),
    NOTE4          VARCHAR(60),
    NOTE5          VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_RUNPARAM 
--

CREATE TABLE TIPS_RUNPARAM(
    WORKDATE         VARCHAR(8)     NOT NULL,
    PARAMTYPENO      VARCHAR(4)     NOT NULL,
    PARAMTYPEDESC    VARCHAR(80),
    DETAILNO         VARCHAR(8),
    DETAILDESC       VARCHAR(80),
    PARAMVALUE       VARCHAR(60),
    NOTE1            VARCHAR(20),
    NOTE2            VARCHAR(20),
    NOTE3            VARCHAR(60),
    NOTE4            VARCHAR(60),
    NOTE5            VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_TAXCODE 
--

CREATE TABLE TIPS_TAXCODE(
    TAXORGCODE      VARCHAR(12)    NOT NULL,
    TAXORGNAME      VARCHAR(60),
    TAXORGTYPE      VARCHAR(1),
    ORGLEVEL        VARCHAR(1),
    UPTRECODE       VARCHAR(10),
    OFNODECODE      VARCHAR(12),
    OFPROVORG       VARCHAR(12),
    OFCITYORG       VARCHAR(12),
    OFCOUNTYORG     VARCHAR(12),
    ADDRESS         VARCHAR(80),
    POSTALCODE      VARCHAR(6),
    PEOPLENAME      VARCHAR(10),
    PEOPLEPHONE     VARCHAR(15),
    PEOPLEMOBILE    VARCHAR(11),
    EMAIL           VARCHAR(60),
    STATUS          VARCHAR(1),
    EFFECTDATE      VARCHAR(8),
    UPDATEAREA      VARCHAR(10),
    UPDATEBATCH     VARCHAR(8),
    NOTE1           VARCHAR(10),
    NOTE2           VARCHAR(20),
    NOTE3           VARCHAR(60),
    NOTE4           VARCHAR(60),
    NOTE5           VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_TAXCODEDTL 
--

CREATE TABLE TIPS_TAXCODEDTL(
    TAXORGCODE      VARCHAR(12)    NOT NULL,
    OPERSIGN        VARCHAR(1)     NOT NULL,
    TAXORGNAME      VARCHAR(60),
    TAXORGTYPE      VARCHAR(1),
    ORGLEVEL        VARCHAR(1),
    UPTRECODE       VARCHAR(10),
    OFNODECODE      VARCHAR(12),
    OFPROVORG       VARCHAR(12),
    OFCITYORG       VARCHAR(12),
    OFCOUNTYORG     VARCHAR(12),
    ADDRESS         VARCHAR(80),
    POSTALCODE      VARCHAR(6),
    PEOPLENAME      VARCHAR(10),
    PEOPLEPHONE     VARCHAR(15),
    PEOPLEMOBILE    VARCHAR(11),
    EMAIL           VARCHAR(60),
    STATUS          VARCHAR(1),
    EFFECTDATE      VARCHAR(8),
    UPDATEAREA      VARCHAR(10),
    UPDATEBATCH     VARCHAR(8),
    NOTE1           VARCHAR(10),
    NOTE2           VARCHAR(20),
    NOTE3           VARCHAR(60),
    NOTE4           VARCHAR(60),
    NOTE5           VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_TAXSUBJECTCODE 
--

CREATE TABLE TIPS_TAXSUBJECTCODE(
    TAXSUBJECTCODE    VARCHAR(10)    NOT NULL,
    TAXORGTYPE        VARCHAR(1)     NOT NULL,
    TAXSUBJECTNAME    VARCHAR(60),
    DESCRIPTION       VARCHAR(80),
    STATUS            VARCHAR(1),
    EFFECTDATE        VARCHAR(8),
    UPDATEAREA        VARCHAR(10),
    UPDATEBATCH       VARCHAR(8),
    NOTE1             VARCHAR(10),
    NOTE2             VARCHAR(20),
    NOTE3             VARCHAR(60),
    NOTE4             VARCHAR(60),
    NOTE5             VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_TAXSUBJECTCODEDTL 
--

CREATE TABLE TIPS_TAXSUBJECTCODEDTL(
    TAXSUBJECTCODE    VARCHAR(10)    NOT NULL,
    TAXORGTYPE        VARCHAR(1)     NOT NULL,
    OPERSIGN          VARCHAR(1)     NOT NULL,
    TAXSUBJECTNAME    VARCHAR(60),
    DESCRIPTION       VARCHAR(80),
    STATUS            VARCHAR(1),
    EFFECTDATE        VARCHAR(8),
    UPDATEAREA        VARCHAR(10),
    UPDATEBATCH       VARCHAR(8),
    NOTE1             VARCHAR(10),
    NOTE2             VARCHAR(20),
    NOTE3             VARCHAR(60),
    NOTE4             VARCHAR(60),
    NOTE5             VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_TAXTYPECODE 
--

CREATE TABLE TIPS_TAXTYPECODE(
    TAXTYPECODE    VARCHAR(10)    NOT NULL,
    TAXORGTYPE     VARCHAR(1)     NOT NULL,
    TAXTYPENAME    VARCHAR(60),
    DESCRIPTION    VARCHAR(80),
    STATUS         VARCHAR(1),
    EFFECTDATE     VARCHAR(8),
    UPDATEAREA     VARCHAR(10),
    UPDATEBATCH    VARCHAR(8),
    NOTE1          VARCHAR(10),
    NOTE2          VARCHAR(20),
    NOTE3          VARCHAR(60),
    NOTE4          VARCHAR(60),
    NOTE5          VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_TAXTYPECODEDTL 
--

CREATE TABLE TIPS_TAXTYPECODEDTL(
    TAXTYPECODE    VARCHAR(10)    NOT NULL,
    TAXORGTYPE     VARCHAR(1)     NOT NULL,
    OPERSIGN       VARCHAR(1)     NOT NULL,
    TAXTYPENAME    VARCHAR(60),
    DESCRIPTION    VARCHAR(80),
    STATUS         VARCHAR(1),
    EFFECTDATE     VARCHAR(8),
    UPDATEAREA     VARCHAR(10),
    UPDATEBATCH    VARCHAR(8),
    NOTE1          VARCHAR(10),
    NOTE2          VARCHAR(20),
    NOTE3          VARCHAR(60),
    NOTE4          VARCHAR(60),
    NOTE5          VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_TRECODE 
--

CREATE TABLE TIPS_TRECODE(
    TRECODE          VARCHAR(12)    NOT NULL,
    TRENAME          VARCHAR(60),
    TRELEVEL         VARCHAR(1),
    PAYBANKNO        VARCHAR(12),
    RECKONTRECODE    VARCHAR(10),
    UPTRECODE        VARCHAR(10),
    OFPROVTREA       VARCHAR(10),
    OFCITYTREA       VARCHAR(10),
    OFCOUNTYTREA     VARCHAR(10),
    OFNODECODE       VARCHAR(12),
    ADDRESS          VARCHAR(80),
    POSTALCODE       VARCHAR(6),
    PEOPLENAME       VARCHAR(10),
    PEOPLEPHONE      VARCHAR(15),
    PEOPLEMOBILE     VARCHAR(11),
    EMAIL            VARCHAR(60),
    STATUS           VARCHAR(1),
    EFFECTDATE       VARCHAR(8),
    UPDATEAREA       VARCHAR(10),
    UPDATEBATCH      VARCHAR(8),
    NOTE1            VARCHAR(10),
    NOTE2            VARCHAR(20),
    NOTE3            VARCHAR(60),
    NOTE4            VARCHAR(60),
    NOTE5            VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_TRECODEDTL 
--

CREATE TABLE TIPS_TRECODEDTL(
    TRECODE          VARCHAR(12)    NOT NULL,
    OPERSIGN         VARCHAR(1)     NOT NULL,
    TRENAME          VARCHAR(60),
    TRELEVEL         VARCHAR(1),
    PAYBANKNO        VARCHAR(12),
    RECKONTRECODE    VARCHAR(10),
    UPTRECODE        VARCHAR(10),
    OFPROVTREA       VARCHAR(10),
    OFCITYTREA       VARCHAR(10),
    OFCOUNTYTREA     VARCHAR(10),
    OFNODECODE       VARCHAR(12),
    ADDRESS          VARCHAR(80),
    POSTALCODE       VARCHAR(6),
    PEOPLENAME       VARCHAR(10),
    PEOPLEPHONE      VARCHAR(15),
    PEOPLEMOBILE     VARCHAR(11),
    EMAIL            VARCHAR(60),
    STATUS           VARCHAR(1),
    EFFECTDATE       VARCHAR(8),
    UPDATEAREA       VARCHAR(10),
    UPDATEBATCH      VARCHAR(8),
    NOTE1            VARCHAR(10),
    NOTE2            VARCHAR(20),
    NOTE3            VARCHAR(60),
    NOTE4            VARCHAR(60),
    NOTE5            VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_VOU_TAXTYPE 
--

CREATE TABLE TIPS_VOU_TAXTYPE(
    SERIALNO             VARCHAR(8)       NOT NULL,
    WORKDATE             VARCHAR(8)       NOT NULL,
    TAXVOUNO             VARCHAR(18)      NOT NULL,
    PROJECTID            VARCHAR(2)       NOT NULL,
    BUDGETSUBJECTCODE    VARCHAR(30),
    LIMITDATE            VARCHAR(8),
    TAXTYPENAME          VARCHAR(60),
    BUDGETLEVELCODE      VARCHAR(1),
    BUDGETLEVELNAME      VARCHAR(60),
    TAXSTARTDATE         VARCHAR(8),
    TAXENDDATE           VARCHAR(8),
    VICESIGN             VARCHAR(35),
    TAXTYPE              VARCHAR(1),
    TAXTYPEAMT           VARCHAR(17),
    DETAILNUM            VARCHAR(8),
    TAXSUBJECTLIST       VARCHAR(2048),
    NOTE1                VARCHAR(20),
    NOTE2                VARCHAR(20),
    NOTE3                VARCHAR(60),
    NOTE4                VARCHAR(60),
    NOTE5                VARCHAR(60)
)
IN AFA_DATA INDEX IN AFA_IDX
;



-- 
-- TABLE: TIPS_BANKCODE 
--

ALTER TABLE TIPS_BANKCODE ADD 
    CONSTRAINT TIPS_BANKCODE_KEY PRIMARY KEY (RECKBANKNO)
;

-- 
-- TABLE: TIPS_BANKCODEDTL 
--

ALTER TABLE TIPS_BANKCODEDTL ADD 
    CONSTRAINT TIPS_BKCODEDTL_PK PRIMARY KEY (RECKBANKNO)
;

-- 
-- TABLE: TIPS_BATCHADM 
--

ALTER TABLE TIPS_BATCHADM ADD 
    CONSTRAINT TIPS_BATCHADM_PK PRIMARY KEY (WORKDATE, BATCHNO, TAXORGCODE)
;

-- 
-- TABLE: TIPS_BATCHDATA 
--

ALTER TABLE TIPS_BATCHDATA ADD 
    CONSTRAINT TIPS_BATCHDATA_PK PRIMARY KEY (WORKDATE, BATCHNO, TAXORGCODE, SERIALNO)
;

-- 
-- TABLE: TIPS_BRANCH_ADM 
--

ALTER TABLE TIPS_BRANCH_ADM ADD 
    CONSTRAINT TIPS_TREADM_KEY_1 PRIMARY KEY (BRNO)
;

-- 
-- TABLE: TIPS_BUDGETSUBJECTCODE 
--

ALTER TABLE TIPS_BUDGETSUBJECTCODE ADD 
    CONSTRAINT TIPS_BGCODE_KEY PRIMARY KEY (BUDGETSUBJECTCODE, SUBJECTTYPE, IESIGN, UPDATEAREA)
;

-- 
-- TABLE: TIPS_BUDGETSUBJECTCODEDTL 
--

ALTER TABLE TIPS_BUDGETSUBJECTCODEDTL ADD 
    CONSTRAINT TIPS_BGCODEDTL_PK PRIMARY KEY (BUDGETSUBJECTCODE, SUBJECTTYPE, IESIGN, UPDATEAREA)
;

-- 
-- TABLE: TIPS_CHECKADM 
--

ALTER TABLE TIPS_CHECKADM ADD 
    CONSTRAINT TIPS_CHKADM_PK PRIMARY KEY (WORKDATE, BATCHNO, PAYBKCODE, PAYEEBANKNO)
;

-- 
-- TABLE: TIPS_CHECKDATA 
--

ALTER TABLE TIPS_CHECKDATA ADD 
    CONSTRAINT TIPS_CHKDTL_PK PRIMARY KEY (WORKDATE, BATCHNO, CORPSERIALNO, PAYBKCODE, PAYEEBANKNO)
;

-- 
-- TABLE: TIPS_CUSTINFO 
--

ALTER TABLE TIPS_CUSTINFO ADD 
    CONSTRAINT TIPS_CUSTINFO_PK PRIMARY KEY (PAYACCT, TAXORGCODE, TAXPAYCODE, PROTOCOLNO)
;

-- 
-- TABLE: TIPS_LIQUIDATE_ADM 
--

ALTER TABLE TIPS_LIQUIDATE_ADM ADD 
    CONSTRAINT TIPS_TREADM_KEY PRIMARY KEY (PAYBKCODE, PAYEEBANKNO)
;

-- 
-- TABLE: TIPS_MAINTRANSDTL 
--

ALTER TABLE TIPS_MAINTRANSDTL ADD 
    CONSTRAINT TIPS_MAINDTL_PK PRIMARY KEY (SERIALNO, WORKDATE)
;

-- 
-- TABLE: TIPS_NODECODE 
--

ALTER TABLE TIPS_NODECODE ADD 
    CONSTRAINT TIPS_NODECODE_KEY PRIMARY KEY (NODECODE)
;

-- 
-- TABLE: TIPS_NODECODEDTL 
--

ALTER TABLE TIPS_NODECODEDTL ADD 
    CONSTRAINT TIPS_NDCODEDTL_PK PRIMARY KEY (NODECODE)
;

-- 
-- TABLE: TIPS_TAXCODE 
--

ALTER TABLE TIPS_TAXCODE ADD 
    CONSTRAINT TIPS_TAXCODE_KEY PRIMARY KEY (TAXORGCODE)
;

-- 
-- TABLE: TIPS_TAXCODEDTL 
--

ALTER TABLE TIPS_TAXCODEDTL ADD 
    CONSTRAINT TIPS_TAXCODEDTL_PK PRIMARY KEY (TAXORGCODE)
;

-- 
-- TABLE: TIPS_TAXSUBJECTCODE 
--

ALTER TABLE TIPS_TAXSUBJECTCODE ADD 
    CONSTRAINT TIPS_TAXSBCODE_KEY PRIMARY KEY (TAXSUBJECTCODE, TAXORGTYPE)
;

-- 
-- TABLE: TIPS_TAXSUBJECTCODEDTL 
--

ALTER TABLE TIPS_TAXSUBJECTCODEDTL ADD 
    CONSTRAINT TIPS_TXSBCDDTL_PK PRIMARY KEY (TAXSUBJECTCODE, TAXORGTYPE)
;

-- 
-- TABLE: TIPS_TAXTYPECODE 
--

ALTER TABLE TIPS_TAXTYPECODE ADD 
    CONSTRAINT TIPS_TAXTPCODE_KEY PRIMARY KEY (TAXTYPECODE, TAXORGTYPE)
;

-- 
-- TABLE: TIPS_TAXTYPECODEDTL 
--

ALTER TABLE TIPS_TAXTYPECODEDTL ADD 
    CONSTRAINT TIPS_TXTPCDDTL_PK PRIMARY KEY (TAXTYPECODE, TAXORGTYPE)
;

-- 
-- TABLE: TIPS_TRECODE 
--

ALTER TABLE TIPS_TRECODE ADD 
    CONSTRAINT TIPS_TRECODE_KEY PRIMARY KEY (TRECODE)
;

-- 
-- TABLE: TIPS_TRECODEDTL 
--

ALTER TABLE TIPS_TRECODEDTL ADD 
    CONSTRAINT TIPS_TRECODEDTL_PK PRIMARY KEY (TRECODE)
;

-- 
-- TABLE: TIPS_VOU_TAXTYPE 
--

ALTER TABLE TIPS_VOU_TAXTYPE ADD 
    CONSTRAINT TIPS_VOU_TXTP_PK PRIMARY KEY (SERIALNO, WORKDATE, TAXVOUNO, PROJECTID)
;


COMMIT WORK;

CONNECT RESET;

TERMINATE;
